/**
 * Topic: Claude Academy
 */
const TOPIC_CLAUDE_ACADEMY = {
  "id": "claude-academy",
  "icon": "🎓",
  "title": "Claude Academy",
  "description": "Anthropic official free courses — AI Fluency (4D Framework), Claude API development, MCP, Claude Code, and prompt engineering",
  "sections": [
    {
      "title": "1. What is Claude Academy?",
      "content": "<p><strong>Claude Academy</strong> (<a href=\"https://academy.claude.com/\" target=\"_blank\">academy.claude.com</a>) is Anthropic's free, self-paced learning platform launched in March 2026. It offers 13+ courses covering AI collaboration skills, API development, and agent building — with certificates upon completion.</p><h4>Course Tracks</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">Track</th><th style=\"text-align:left; padding:0.5rem;\">Audience</th><th style=\"text-align:left; padding:0.5rem;\">Courses</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">AI Fluency</td><td style=\"padding:0.5rem;\">Everyone (no-code)</td><td style=\"padding:0.5rem;\">Framework & Foundations, for Students, for Small Business, for Nonprofits, for Educators, for Builders</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Build with Claude</td><td style=\"padding:0.5rem;\">Developers</td><td style=\"padding:0.5rem;\">Claude 101, Building with Claude API, Claude Code, MCP, Agent Skills</td></tr><tr><td style=\"padding:0.5rem;\">Cloud Integration</td><td style=\"padding:0.5rem;\">DevOps/Cloud</td><td style=\"padding:0.5rem;\">Claude on AWS Bedrock, Claude on Google Vertex AI</td></tr></table><h4>Key Features</h4><ul><li><strong>100% free</strong> — No payment required</li><li><strong>Self-paced</strong> — 150+ lessons across all courses</li><li><strong>Certificates</strong> — Completion certificates for each course</li><li><strong>Practical</strong> — Hands-on exercises, not just theory</li><li><strong>Also on Coursera</strong> — Available on Coursera for credit</li></ul>"
    },
    {
      "title": "2. AI Fluency: The 4D Framework",
      "content": "<p>The core of Claude Academy is the <strong>4D Framework</strong> — four competencies for effective human-AI collaboration:</p><pre><code>┌──────────────────────────────────────────────────────────┐\n│                    4D Framework                           │\n│                                                           │\n│   Outer Loop (Strategic):                                │\n│   ┌─────────────────┐     ┌─────────────────┐           │\n│   │   DELEGATION    │     │   DILIGENCE     │           │\n│   │ \"Should AI do   │     │ \"Am I using AI  │           │\n│   │  this task?\"    │     │  responsibly?\"  │           │\n│   └────────┬────────┘     └────────┬────────┘           │\n│            │                        │                     │\n│   Inner Loop (Tactical):           │                     │\n│   ┌────────▼────────┐     ┌────────▼────────┐           │\n│   │  DESCRIPTION    │────▶│  DISCERNMENT    │           │\n│   │ \"How do I       │     │ \"Is this output │           │\n│   │  communicate?\"  │◀────│  good enough?\"  │           │\n│   └─────────────────┘     └─────────────────┘           │\n│                                                           │\n└──────────────────────────────────────────────────────────┘</code></pre><h4>The 4 Ds Explained</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">D</th><th style=\"text-align:left; padding:0.5rem;\">Competency</th><th style=\"text-align:left; padding:0.5rem;\">Key Question</th><th style=\"text-align:left; padding:0.5rem;\">Skills</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><strong>Delegation</strong></td><td style=\"padding:0.5rem;\">Task Selection</td><td style=\"padding:0.5rem;\">\"Should AI do this, or should I?\"</td><td style=\"padding:0.5rem;\">Identify AI-suitable tasks; know limits; preserve human judgment</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><strong>Description</strong></td><td style=\"padding:0.5rem;\">Communication</td><td style=\"padding:0.5rem;\">\"How do I clearly express what I need?\"</td><td style=\"padding:0.5rem;\">Prompt crafting; context; constraints; examples; persona</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><strong>Discernment</strong></td><td style=\"padding:0.5rem;\">Evaluation</td><td style=\"padding:0.5rem;\">\"Is this output accurate and useful?\"</td><td style=\"padding:0.5rem;\">Verify claims; detect hallucination; iterative refinement</td></tr><tr><td style=\"padding:0.5rem;\"><strong>Diligence</strong></td><td style=\"padding:0.5rem;\">Responsibility</td><td style=\"padding:0.5rem;\">\"Am I using AI ethically and safely?\"</td><td style=\"padding:0.5rem;\">Privacy; bias; transparency; attribution; organizational policy</td></tr></table>"
    },
    {
      "title": "3. Building with the Claude API",
      "content": "<p>The developer course covers the full Claude API from basics to production agent architectures.</p><h4>Course Modules</h4><ul><li><strong>API Fundamentals</strong> — SDK setup, authentication, model parameters, streaming</li><li><strong>Prompt Engineering</strong> — System prompts, multi-turn, structured output (JSON mode)</li><li><strong>Multimodal</strong> — Images, PDFs, documents in prompts</li><li><strong>Tool Use (Function Calling)</strong> — Define tools, handle tool results, multi-step reasoning</li><li><strong>RAG (Retrieval-Augmented Generation)</strong> — Embeddings, vector search, citation</li><li><strong>Agents</strong> — Agentic loops, deterministic workflows, autonomous agents</li><li><strong>Production</strong> — Error handling, rate limits, caching, evaluation</li></ul><h4>Quick Start</h4><pre><code># Install\npip install anthropic\n\n# Basic API call\nimport anthropic\nclient = anthropic.Anthropic()  # reads ANTHROPIC_API_KEY env var\n\nresponse = client.messages.create(\n    model=\"claude-sonnet-4-20250514\",\n    max_tokens=1024,\n    messages=[{\"role\": \"user\", \"content\": \"Explain eBPF in one paragraph\"}]\n)\nprint(response.content[0].text)</code></pre><h4>Tool Use Example</h4><pre><code>tools = [{\n    \"name\": \"get_pcie_errors\",\n    \"description\": \"Get PCIe AER error count for a device\",\n    \"input_schema\": {\n        \"type\": \"object\",\n        \"properties\": {\n            \"device\": {\"type\": \"string\", \"description\": \"BDF address\"}\n        },\n        \"required\": [\"device\"]\n    }\n}]\n\nresponse = client.messages.create(\n    model=\"claude-sonnet-4-20250514\",\n    tools=tools,\n    messages=[{\"role\": \"user\", \"content\": \"How many PCIe errors on 0000:03:00.0?\"}]\n)\n# Claude responds with tool_use block → you execute → return result</code></pre>"
    },
    {
      "title": "4. Claude Code",
      "content": "<p><strong>Claude Code</strong> is Anthropic's AI-powered terminal coding agent. The Academy course teaches how to use it for real software development.</p><h4>Key Capabilities</h4><ul><li>Understands entire codebases (reads files, follows imports)</li><li>Edits multiple files atomically</li><li>Runs terminal commands (build, test, git)</li><li>Creates PRs, fixes CI failures</li><li>Works in any language/framework</li></ul><h4>Usage Patterns</h4><pre><code># Start Claude Code in a project\ncd my-project\nclaude\n\n# Common prompts:\n\"Add error handling to the storage collector\"\n\"Write unit tests for the correlator engine\"\n\"Fix the failing CI test and push\"\n\"Refactor this function to use async/await\"\n\"Explain how the event bus works\"</code></pre><h4>Best Practices from Academy</h4><ul><li><strong>Start with context</strong> — \"Look at src/collectors/pcie.py and add a similar collector for GPU\"</li><li><strong>Be specific about constraints</strong> — \"Use dataclasses, no external dependencies, follow existing patterns\"</li><li><strong>Iterate</strong> — Review output, provide feedback, refine</li><li><strong>Use CLAUDE.md</strong> — Project-level instructions file that Claude Code reads automatically</li><li><strong>Trust but verify</strong> — Always review changes before committing</li></ul>"
    },
    {
      "title": "5. Model Context Protocol (MCP)",
      "content": "<p><strong>MCP (Model Context Protocol)</strong> is a standard for connecting AI models to external tools and data sources. The Academy teaches how to build and use MCP servers.</p><h4>MCP Architecture</h4><pre><code>┌──────────────┐     ┌──────────────┐     ┌──────────────┐\n│  Claude      │────▶│  MCP Client  │────▶│  MCP Server  │\n│  (AI Model)  │◀────│  (in host)   │◀────│  (tool/data) │\n└──────────────┘     └──────────────┘     └──────────────┘\n                                                  │\n                                           ┌──────┴──────┐\n                                           │ File system  │\n                                           │ Database     │\n                                           │ API          │\n                                           │ Git repo     │\n                                           └─────────────┘</code></pre><h4>MCP Primitives</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">Primitive</th><th style=\"text-align:left; padding:0.5rem;\">Direction</th><th style=\"text-align:left; padding:0.5rem;\">Purpose</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Tools</td><td style=\"padding:0.5rem;\">Model → Server</td><td style=\"padding:0.5rem;\">Model invokes functions (read file, query DB, call API)</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Resources</td><td style=\"padding:0.5rem;\">Server → Model</td><td style=\"padding:0.5rem;\">Server provides data/context (file content, DB schemas)</td></tr><tr><td style=\"padding:0.5rem;\">Prompts</td><td style=\"padding:0.5rem;\">Server → Model</td><td style=\"padding:0.5rem;\">Server provides prompt templates for specific workflows</td></tr></table><h4>Building an MCP Server</h4><pre><code># pip install mcp\nfrom mcp.server import Server\nfrom mcp.types import Tool\n\nserver = Server(\"hw-diag-mcp\")\n\n@server.tool()\nasync def get_pcie_errors(device: str) -> str:\n    \"\"\"Get PCIe AER error count for a device.\"\"\"\n    # Read from /sys/bus/pci/devices/{device}/aer_dev_correctable\n    # Return formatted result\n    return f\"Device {device}: 5 correctable errors\"\n\n@server.tool()\nasync def get_nvme_health(device: str) -> str:\n    \"\"\"Get NVMe SMART health summary.\"\"\"\n    # Run nvme smart-log\n    return f\"Device {device}: healthy, 35C, 5% used\"</code></pre>"
    },
    {
      "title": "6. Prompt Engineering Best Practices",
      "content": "<h4>From AI Fluency Course — Description Skills</h4><pre><code># Structure of an effective prompt:\n\n1. ROLE: Who should Claude be?\n   \"You are a senior Linux kernel engineer specializing in eBPF.\"\n\n2. CONTEXT: What background is needed?\n   \"We have a PCIe AER monitoring tool that uses BCC Python bindings.\"\n\n3. TASK: What exactly should Claude do?\n   \"Add a new collector for NVMe queue depth saturation.\"\n\n4. CONSTRAINTS: What rules to follow?\n   \"Follow the existing BaseCollector pattern. Use dataclasses for events.\n    No external dependencies beyond BCC.\"\n\n5. OUTPUT FORMAT: How should the answer look?\n   \"Provide the complete Python file with docstrings and type hints.\"\n\n6. EXAMPLES: (Optional) Show desired input/output\n   \"Similar to collectors/pcie.py but for block:block_rq_issue tracepoint.\"</code></pre><h4>Techniques</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">Technique</th><th style=\"text-align:left; padding:0.5rem;\">When to Use</th><th style=\"text-align:left; padding:0.5rem;\">Example</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Chain of Thought</td><td style=\"padding:0.5rem;\">Complex reasoning</td><td style=\"padding:0.5rem;\">\"Think step by step about the root cause...\"</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Few-shot Examples</td><td style=\"padding:0.5rem;\">Specific format needed</td><td style=\"padding:0.5rem;\">Show 2-3 input→output examples</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">XML Tags</td><td style=\"padding:0.5rem;\">Structured input</td><td style=\"padding:0.5rem;\">&lt;context&gt;...&lt;/context&gt; &lt;task&gt;...&lt;/task&gt;</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">System Prompt</td><td style=\"padding:0.5rem;\">Persistent behavior</td><td style=\"padding:0.5rem;\">Set role, tone, constraints for entire conversation</td></tr><tr><td style=\"padding:0.5rem;\">Prefilling</td><td style=\"padding:0.5rem;\">Force format</td><td style=\"padding:0.5rem;\">Start assistant response with \"```python\\n\"</td></tr></table>"
    },
    {
      "title": "7. Learning Path & Certification",
      "content": "<h4>Recommended Order</h4><pre><code>Beginner:\n  1. Claude 101 (basics, desktop app, Projects)\n  2. AI Fluency: Framework & Foundations (4D Framework)\n\nIntermediate:\n  3. AI Fluency for Builders (applying 4D to software)\n  4. Building with the Claude API (SDK, tools, RAG)\n\nAdvanced:\n  5. Claude Code (terminal agent for coding)\n  6. Model Context Protocol (MCP servers + tools)\n  7. Agent Skills & Subagents (autonomous systems)\n\nSpecialization:\n  8. Claude on AWS Bedrock / Google Vertex AI</code></pre><h4>Certification</h4><ul><li>Each course provides a <strong>completion certificate</strong></li><li><strong>Claude Certified Architect</strong> — Advanced exam available</li><li>Certificates are verifiable and shareable</li><li>Also available on <strong>Coursera</strong> for professional development credit</li></ul><h4>GitHub Resources</h4><pre><code># Anthropic official course materials (Jupyter notebooks)\ngit clone https://github.com/anthropics/courses.git\n\n# Contains:\n# - anthropic_api_fundamentals/\n# - prompt_engineering_interactive_tutorial/\n# - tool_use/\n# - real_world_prompting/\n# - prompt_evaluations/</code></pre><p><strong>References:</strong></p><ul><li><a href=\"https://academy.claude.com/\" target=\"_blank\">Claude Academy</a></li><li><a href=\"https://www.anthropic.com/learn\" target=\"_blank\">Anthropic Learn</a></li><li><a href=\"https://docs.anthropic.com/\" target=\"_blank\">Claude API Documentation</a></li><li><a href=\"https://github.com/anthropics/courses\" target=\"_blank\">Anthropic Courses (GitHub)</a></li><li><a href=\"https://modelcontextprotocol.io/\" target=\"_blank\">MCP Specification</a></li></ul>"
    }
  ]
};
