/**
 * Topic: Users & Permissions
 */
const TOPIC_USERS = {
  "id": "users",
  "category": "core",
  "icon": "👥",
  "title": "Users & Permissions",
  "description": "Manage Linux accounts and access — users, UIDs & the account files, groups, passwords & aging, sudo/privilege escalation, sessions, and account-security best practices",
  "keywords": [
    "user", "users", "permissions", "uid", "gid", "passwd", "shadow",
    "group", "groups", "useradd", "usermod", "userdel", "groupadd",
    "password", "chage", "aging", "pam", "sudo", "sudoers", "visudo",
    "su", "root", "privilege", "escalation", "login", "shell", "skel",
    "id", "whoami", "getent", "nologin", "least privilege", "ssh key"
  ],
  "sections": [
    {
      "title": "1. Users, UIDs & the Account Files",
      "content": "<p>Every Linux user has a numeric <strong>UID</strong> (user ID) and belongs to one or more <strong>groups</strong> (each a <strong>GID</strong>). Names are for humans; the kernel enforces permissions by UID/GID.</p><h4>The account files</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">File</th><th style=\"text-align:left; padding:0.5rem;\">Holds</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>/etc/passwd</code></td><td style=\"padding:0.5rem;\">User accounts (world-readable, no passwords)</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>/etc/shadow</code></td><td style=\"padding:0.5rem;\">Hashed passwords + aging (root-only)</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>/etc/group</code></td><td style=\"padding:0.5rem;\">Groups and their members</td></tr><tr><td style=\"padding:0.5rem;\"><code>/etc/gshadow</code></td><td style=\"padding:0.5rem;\">Group passwords/admins (root-only)</td></tr></table><h4>Reading /etc/passwd</h4><pre><code># name : x : UID : GID : comment(GECOS) : home : login-shell\nalice:x:1000:1000:Alice:/home/alice:/bin/bash\n#      │    │    │                      │        └ shell (/usr/sbin/nologin = no login)\n#      │    │    └ primary GID          └ home directory\n#      │    └ UID\n#      └ 'x' = password is in /etc/shadow\n\ngetent passwd alice        # look up an account (works with LDAP/NSS too)\ngetent passwd 1000         # by UID</code></pre><h4>System vs regular users</h4><pre><code># UID ranges (typical):\n#   0        root (the superuser -- unlimited privilege)\n#   1-999    system/service accounts (daemons; usually 'nologin' shell)\n#   1000+    regular human users\n\ncat /etc/login.defs | grep -E 'UID_MIN|UID_MAX'   # the configured ranges\nid alice                   # uid, gid, and all groups for a user\nid                          # your own identity</code></pre>"
    },
    {
      "title": "2. Managing Users",
      "content": "<h4>Create, modify, delete</h4><pre><code># Create a user WITH a home dir and bash shell\nsudo useradd -m -s /bin/bash alice\nsudo passwd alice            # set the initial password\n\n# Create a system/service account (no home, no login)\nsudo useradd -r -s /usr/sbin/nologin appsvc\n\n# Modify\nsudo usermod -aG docker alice     # ADD to a group (-a is essential: append)\nsudo usermod -s /bin/zsh alice    # change login shell\nsudo usermod -L alice             # LOCK the account (disable password login)\nsudo usermod -U alice             # unlock\nsudo usermod -l newname oldname   # rename\n\n# Delete\nsudo userdel alice                # keep the home directory\nsudo userdel -r alice             # also remove home + mail spool</code></pre><h4>useradd caution: -aG vs -G</h4><pre><code># WRONG: usermod -G docker alice   -> REPLACES all supplementary groups!\n# RIGHT: usermod -aG docker alice  -> APPENDS (keeps existing groups)\n# Forgetting -a is a classic way to accidentally remove someone from sudo.</code></pre><h4>Skeleton & defaults</h4><pre><code># New home dirs are populated from /etc/skel (dotfiles template):\nls -la /etc/skel\n# Defaults for useradd live in /etc/default/useradd and /etc/login.defs.\nuseradd -D                 # show the current useradd defaults</code></pre>"
    },
    {
      "title": "3. Groups",
      "content": "<p>Groups let you grant a set of users shared access. Each user has one <strong>primary group</strong> (from <code>/etc/passwd</code>) and any number of <strong>supplementary groups</strong>.</p><h4>Managing groups</h4><pre><code>sudo groupadd developers          # create a group\nsudo groupdel developers          # delete\nsudo groupmod -n devs developers  # rename\n\nsudo usermod -aG developers alice # add alice (append!)\nsudo gpasswd -d alice developers  # remove alice from the group\nsudo gpasswd -A bob developers    # make bob a group administrator\n\ngetent group developers           # list members\ngroups alice                      # groups a user belongs to\nid -Gn alice                      # same, space-separated names</code></pre><h4>Primary vs supplementary</h4><pre><code># Files a user CREATES get their PRIMARY group by default.\nsudo usermod -g staff alice       # change alice's primary group\n\n# Switch your active primary group for a shell session:\nnewgrp developers                 # new files now get group 'developers'\n\n# A common pattern: a shared directory with setgid so ALL new files inherit\n# the group (see the File System topic for setgid):\nsudo chgrp developers /srv/shared\nsudo chmod 2775 /srv/shared       # 2 = setgid bit</code></pre>"
    },
    {
      "title": "4. Passwords, Aging & Authentication",
      "content": "<h4>Passwords & /etc/shadow</h4><pre><code>passwd                     # change YOUR password\nsudo passwd alice          # set/reset another user's password\nsudo passwd -l alice       # lock (prepends ! to the hash)\nsudo passwd -e alice       # EXPIRE now -> force change at next login\n\n# /etc/shadow fields:\n# name : hash : lastchg : min : max : warn : inactive : expire :\n#   hash: $6$... ($6 = SHA-512).  '!' or '*' = no valid password (locked)</code></pre><h4>Password aging with chage</h4><pre><code>sudo chage -l alice        # show aging info (expiry, last change)\nsudo chage -M 90 alice     # password must change every 90 days\nsudo chage -m 7 alice      # minimum 7 days between changes\nsudo chage -W 14 alice     # warn 14 days before expiry\nsudo chage -E 2026-12-31 alice   # account expires on this date</code></pre><h4>PAM — the pluggable auth framework</h4><pre><code># Authentication is handled by PAM (Pluggable Authentication Modules), not\n# hard-coded. Policy lives under /etc/pam.d/ (one file per service):\nls /etc/pam.d/             # login, sshd, sudo, common-auth, ...\n\n# PAM controls password strength (pam_pwquality), account lockout after\n# failed attempts (pam_faillock), 2FA modules, LDAP/Kerberos auth, etc.\n# You configure security POLICY here rather than in each application.</code></pre>"
    },
    {
      "title": "5. Ownership & Permissions",
      "content": "<p>Access to a file is decided by its owner/group and its permission bits. (For the full treatment — inodes, ACLs, umask — see the <strong>File System</strong> topic; here's the user-facing summary.)</p><h4>The model</h4><pre><code>ls -l file\n#   -rw-r----- 1 alice devs 0 ... file\n#    │  │  │     └owner  └group\n#    │  │  └ others: ---   (no access)\n#    │  └─── group:  r--   (read)\n#    └────── owner:  rw-   (read+write)\n\nchmod 640 file             # rw-r-----  (octal: r=4 w=2 x=1)\nchmod u+x,g-w file         # symbolic\nchown alice:devs file      # set owner and group\nchgrp devs file            # group only</code></pre><h4>Who am I / can I?</h4><pre><code>id                         # your UID/GID/groups (what the kernel checks)\nsudo -l                    # what commands you may run via sudo\n\n# A process runs with the user's identity; permission checks compare the\n# process's effective UID/GID against the file's owner/group/other bits.</code></pre><h4>Special bits recap</h4><pre><code># setuid (4xxx): run a program as its OWNER (e.g. /usr/bin/passwd runs as root)\n# setgid (2xxx): on a dir, new files inherit the dir's group\n# sticky (1xxx): on a shared dir, only the owner can delete their files (/tmp)\nfind / -perm -4000 -type f 2>/dev/null   # audit setuid binaries (security!)</code></pre>"
    },
    {
      "title": "6. sudo & Privilege Escalation",
      "content": "<p><strong>sudo</strong> lets permitted users run commands as another user (usually root) with per-command control and full logging — far safer than sharing the root password.</p><h4>Editing sudo policy (always via visudo)</h4><pre><code>sudo visudo                # edits /etc/sudoers with a SYNTAX CHECK on save\nsudo visudo -f /etc/sudoers.d/alice   # a drop-in file (preferred)\n\n# sudoers rule format:\n#   who   where = (as-whom)      what\nalice    ALL   = (ALL:ALL)       ALL           # alice can run anything\n%devs    ALL   = (ALL)  NOPASSWD: ALL          # group 'devs', no password\nbob      ALL   = (ALL)  /usr/bin/systemctl restart nginx  # ONE command only\n\n# NEVER edit /etc/sudoers with a normal editor -- a syntax error can lock\n# everyone out of sudo. visudo validates before saving.</code></pre><h4>Using sudo</h4><pre><code>sudo command               # run one command as root\nsudo -u appsvc command     # run as a specific user\nsudo -i                    # start a full root LOGIN shell (root's env)\nsudo -s                    # root shell keeping your environment\nsudo -l                    # list what YOU are allowed to run\nsudo -k                    # forget the cached credentials now</code></pre><h4>su vs sudo, and logging</h4><pre><code>su -                       # switch to root (needs the ROOT password)\nsu - alice                 # become alice (needs alice's password or root)\n# Prefer sudo: it uses the CALLER's password, is per-command, and is logged:\njournalctl -e /usr/bin/sudo        # audit sudo usage\ngrep sudo /var/log/auth.log         # (Debian/Ubuntu)</code></pre>"
    },
    {
      "title": "7. Identity, Sessions & Shells",
      "content": "<h4>Who is logged in / what happened</h4><pre><code>whoami                     # current effective username\nwho                        # who is logged in now\nw                          # who + what they're running + load\nlast                       # login history (from /var/log/wtmp)\nlastlog                    # last login time per account\nloginctl list-sessions     # systemd-tracked login sessions</code></pre><h4>Login vs non-login, interactive vs not</h4><pre><code># Which startup files run depends on the shell type:\n#   Login shell     (ssh, console, 'su -')  -> /etc/profile, ~/.bash_profile\n#   Interactive non-login (new terminal tab) -> ~/.bashrc\n#   Non-interactive (a script)               -> neither (unless BASH_ENV)\n#\n# This is why a PATH you set in ~/.bashrc may not apply over ssh, and vice\n# versa. Put login-shell env in ~/.profile; interactive tweaks in ~/.bashrc.\n\nchsh -s /bin/zsh           # change your own login shell\ngetent passwd alice | cut -d: -f7   # see a user's configured shell</code></pre><h4>Service accounts get no shell</h4><pre><code># Daemons should not be able to log in. Give them a nologin shell:\nsudo usermod -s /usr/sbin/nologin appsvc\n# Attempts to log in as appsvc are refused with a polite message.</code></pre>"
    },
    {
      "title": "8. Account Security Best Practices",
      "content": "<h4>Principle of least privilege</h4><ul><li>Use regular accounts + <strong>sudo</strong> for admin tasks; don't work as root day-to-day.</li><li>Grant the <strong>narrowest</strong> sudoers rule that works (specific commands, not <code>ALL</code>).</li><li>Give service accounts a <code>nologin</code> shell and only the access they need.</li></ul><h4>Hardening the login surface</h4><pre><code># Prefer SSH KEYS over passwords, then disable password/root SSH login:\n#   /etc/ssh/sshd_config\n#     PermitRootLogin no\n#     PasswordAuthentication no\nsudo systemctl reload sshd\n\n# Lock or expire accounts that shouldn't log in:\nsudo passwd -l olduser      # lock the password\nsudo usermod -s /usr/sbin/nologin olduser\nsudo chage -E 0 olduser     # expire the account immediately</code></pre><h4>Auditing</h4><pre><code># Accounts that can log in (have a real shell):\ngetent passwd | awk -F: '$7 !~ /nologin|false/ {print $1, $7}'\n\n# Empty-password accounts (should be NONE):\nsudo awk -F: '($2 == \"\") {print $1}' /etc/shadow\n\n# Everyone who can use sudo:\ngetent group sudo wheel 2>/dev/null\n\n# setuid-root binaries (each is a potential escalation path):\nfind / -perm -4000 -user root -type f 2>/dev/null</code></pre><h4>Checklist</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">Do</th><th style=\"text-align:left; padding:0.5rem;\">Why</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Disable direct root login</td><td style=\"padding:0.5rem;\">Force accountable, logged sudo use</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">SSH keys, not passwords</td><td style=\"padding:0.5rem;\">Resist brute force &amp; credential leaks</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Password aging + lockout (PAM)</td><td style=\"padding:0.5rem;\">Limit stale/weak credentials</td></tr><tr><td style=\"padding:0.5rem;\">Regularly audit sudo &amp; setuid</td><td style=\"padding:0.5rem;\">Catch privilege creep early</td></tr></table><p><strong>References:</strong></p><ul><li><a href=\"https://man7.org/linux/man-pages/man5/passwd.5.html\" target=\"_blank\">passwd(5) — /etc/passwd format</a></li><li><a href=\"https://man7.org/linux/man-pages/man5/shadow.5.html\" target=\"_blank\">shadow(5) — /etc/shadow format</a></li><li><a href=\"https://man7.org/linux/man-pages/man8/useradd.8.html\" target=\"_blank\">useradd(8) — man page</a></li><li><a href=\"https://man7.org/linux/man-pages/man5/sudoers.5.html\" target=\"_blank\">sudoers(5) — sudo policy reference</a></li><li><a href=\"https://man7.org/linux/man-pages/man8/pam.8.html\" target=\"_blank\">pam(8) — Pluggable Authentication Modules</a></li></ul>"
    }
  ]
};
