/**
 * Topic: Input Drivers
 */
const TOPIC_INPUT_DRIVERS = {
  "id": "input-drivers",
  "category": "drivers",
  "icon": "🕹️",
  "title": "Input Drivers",
  "description": "Linux input subsystem drivers — keyboards, mice, touchscreens & buttons — the event model (type/code/value), registering an input_dev, reporting events, evdev & /dev/input, and user-space tools, with flow charts throughout",
  "keywords": [
    "input driver", "input subsystem", "input_dev", "evdev", "event",
    "input_event", "ev_key", "ev_rel", "ev_abs", "ev_syn", "input_sync",
    "input_report_key", "input_report_abs", "keyboard", "mouse",
    "touchscreen", "button", "gpio key", "joystick", "multitouch",
    "/dev/input", "eventX", "evtest", "libinput", "xinput", "input_register_device",
    "abs params", "autorepeat", "keycode"
  ],
  "sections": [
    {
      "title": "1. The Linux Input Subsystem",
      "content": "<p>The <strong>input subsystem</strong> gives every input device — keyboard, mouse, touchscreen, joystick, a single GPIO button — one unified way to deliver events to user space. Your driver only has to describe <em>what</em> happened (a key went down, a wheel moved); the subsystem handles delivery, device nodes, and the standard event format.</p><h4>Architecture — from hardware to app</h4><pre><code>┌───────────────────────────────────────────────────────────────┐\n│ USER SPACE   X11 / Wayland / libinput  ── read /dev/input/eventX │\n└─────────────────────────────────┬─────────────────────────────┘\n                                   │ read() of struct input_event\n════════════════════════════════════▼════════════════════════════ user/kernel\n┌───────────────────────────────────────────────────────────────┐\n│ INPUT HANDLER  evdev  ── exposes /dev/input/eventX, buffers      │\n│                (other handlers: mousedev, joydev, keyboard/VT)   │\n├───────────────────────────────────────────────────────────────┤\n│ INPUT CORE  (input.c)  ── routes events, matches devices↔handlers│\n├───────────────────────────────────────────────────────────────┤\n│ YOUR INPUT DEVICE DRIVER  ── describes capabilities, reports     │\n│                              events via input_report_*()          │\n├───────────────────────────────────────────────────────────────┤\n│ HARDWARE   keyboard matrix / mouse / touch controller / GPIO     │\n└───────────────────────────────────────────────────────────────┘\n#\n# You implement ONLY the second-from-bottom box. The input core + evdev give\n# you /dev/input/eventX and a stable event format for free. (An input device\n# node is a character device -- see the Character Drivers topic.)</code></pre><h4>Why it exists</h4><pre><code># Before the input subsystem, every keyboard/mouse driver invented its own\n# interface. Now:\n#   - ONE event format (struct input_event) for ALL device types\n#   - device nodes created automatically (/dev/input/eventX)\n#   - handlers (evdev) shared by every driver -- write less code\n#   - X/Wayland/libinput read one well-known interface</code></pre>"
    },
    {
      "title": "2. The Event Model: type / code / value",
      "content": "<p>Every input action is expressed as one or more <strong>events</strong>. Each event has three fields — a <strong>type</strong> (category), a <strong>code</strong> (which key/axis), and a <strong>value</strong> (state or delta).</p><h4>struct input_event</h4><pre><code>struct input_event {\n    struct timeval time;   // when it happened\n    __u16 type;            // EV_KEY, EV_REL, EV_ABS, EV_SYN, ...\n    __u16 code;            // KEY_A, REL_X, ABS_X, SYN_REPORT, ...\n    __s32 value;           // key: 1=press 0=release 2=autorepeat\n                           // rel: signed delta   abs: absolute position\n};</code></pre><h4>The main event types</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">Type</th><th style=\"text-align:left; padding:0.5rem;\">Meaning</th><th style=\"text-align:left; padding:0.5rem;\">Example code / value</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>EV_KEY</code></td><td style=\"padding:0.5rem;\">Keys &amp; buttons</td><td style=\"padding:0.5rem;\">KEY_A, BTN_LEFT / 0,1,2</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>EV_REL</code></td><td style=\"padding:0.5rem;\">Relative axes (mouse)</td><td style=\"padding:0.5rem;\">REL_X, REL_Y, REL_WHEEL / delta</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>EV_ABS</code></td><td style=\"padding:0.5rem;\">Absolute axes (touch)</td><td style=\"padding:0.5rem;\">ABS_X, ABS_Y / coordinate</td></tr><tr><td style=\"padding:0.5rem;\"><code>EV_SYN</code></td><td style=\"padding:0.5rem;\">Synchronization</td><td style=\"padding:0.5rem;\">SYN_REPORT — \"packet done\"</td></tr></table><h4>How one action becomes events</h4><pre><code># Pressing the 'A' key:\n#   EV_KEY  KEY_A     1      (down)\n#   EV_SYN  SYN_REPORT 0     (end of this event packet)\n#   ... later ...\n#   EV_KEY  KEY_A     0      (up)\n#   EV_SYN  SYN_REPORT 0\n\n# Moving a mouse diagonally by (+3,-2):\n#   EV_REL  REL_X     3\n#   EV_REL  REL_Y    -2\n#   EV_SYN  SYN_REPORT 0     <- groups the X and Y into ONE movement\n#\n# The EV_SYN/SYN_REPORT is essential: it tells user space \"the events since\n# the last SYN form ONE complete update\" (so X and Y arrive together).</code></pre>"
    },
    {
      "title": "3. Registering an input_dev",
      "content": "<p>A driver allocates an <code>input_dev</code>, declares which events it can generate (its <strong>capabilities</strong>), then registers it. Declaring capabilities is what lets user space know it's a keyboard vs a mouse vs a touchscreen.</p><h4>Allocate, describe, register</h4><pre><code>#include <linux/input.h>\n\nstatic struct input_dev *button_dev;\n\nstatic int my_probe(struct platform_device *pdev)\n{\n    int err;\n\n    button_dev = input_allocate_device();\n    if (!button_dev)\n        return -ENOMEM;\n\n    button_dev->name = \"GPIO Button\";\n    button_dev->phys = \"gpio-keys/input0\";\n    button_dev->id.bustype = BUS_HOST;\n\n    // Declare capabilities: we generate EV_KEY events, specifically KEY_ENTER\n    input_set_capability(button_dev, EV_KEY, KEY_ENTER);\n    // (equivalent low-level form:)\n    //   set_bit(EV_KEY, button_dev->evbit);\n    //   set_bit(KEY_ENTER, button_dev->keybit);\n\n    err = input_register_device(button_dev);   // publish -> /dev/input/eventX\n    if (err) {\n        input_free_device(button_dev);          // only free if NOT registered\n        return err;\n    }\n    return 0;\n}\n\nstatic void my_remove(struct platform_device *pdev)\n{\n    input_unregister_device(button_dev);   // this also frees the device\n}</code></pre><h4>Registration flow</h4><pre><code>probe()\n   │\n   ▼\ninput_allocate_device()          ── get a blank input_dev\n   │\n   ▼\nset name / phys / id\n   │\n   ▼\ndeclare capabilities             ── EV_KEY + KEY_*, EV_REL + REL_*, etc.\n   │  (input_set_capability / set_bit)\n   ▼\ninput_register_device()          ── input core matches it to evdev\n   │                                  -> /dev/input/eventX appears\n   ▼\nready: hardware events -> input_report_*() -> user space\n#\n# Cleanup: input_unregister_device() frees a REGISTERED device.\n# Use input_free_device() ONLY to undo an allocate that was never registered.</code></pre>"
    },
    {
      "title": "4. Reporting Events",
      "content": "<p>When the hardware signals activity (usually via an interrupt), the driver <strong>reports</strong> the event and then calls <code>input_sync()</code> to mark the packet complete.</p><h4>The report helpers</h4><pre><code>input_report_key(dev, KEY_ENTER, 1);   // key/button: value 1=down, 0=up\ninput_report_rel(dev, REL_X, dx);      // relative axis: signed delta\ninput_report_abs(dev, ABS_X, x);       // absolute axis: position\ninput_sync(dev);                       // \"packet done\" -> emits SYN_REPORT\n// Forgetting input_sync() is the #1 bug -- events buffer but never surface.</code></pre><h4>Event-report flow (a GPIO button)</h4><pre><code>button pressed ─► GPIO line changes ─► IRQ fires\n   │\n   ▼\nbutton_isr():\n   state = gpio_get_value(gpio)          // 0 or 1\n   input_report_key(button_dev, KEY_ENTER, state)\n   input_sync(button_dev)               // finalize the packet\n   │\n   ▼\ninput core ─► evdev handler ─► buffered in /dev/input/eventX\n   │\n   ▼\nuser space read() returns an input_event (EV_KEY) + (EV_SYN)</code></pre><pre><code>// Interrupt handler for a single GPIO button\nstatic irqreturn_t button_isr(int irq, void *dev_id)\n{\n    int state = gpio_get_value(BUTTON_GPIO);   // read the line\n    input_report_key(button_dev, KEY_ENTER, state);\n    input_sync(button_dev);\n    return IRQ_HANDLED;\n}\n// Request the IRQ on both edges so press AND release are reported:\n//   request_irq(irq, button_isr,\n//               IRQF_TRIGGER_RISING | IRQF_TRIGGER_FALLING, \"gpio-btn\", NULL);\n// (See the GPIO topic for line/IRQ setup, and Character Drivers for the\n//  cdev fundamentals under /dev/input.)</code></pre><h4>Mouse example</h4><pre><code>// Report a relative movement of (dx, dy) plus a left-button state:\ninput_report_rel(mouse_dev, REL_X, dx);\ninput_report_rel(mouse_dev, REL_Y, dy);\ninput_report_key(mouse_dev, BTN_LEFT, left_pressed);\ninput_sync(mouse_dev);      // X, Y and button delivered as ONE update</code></pre>"
    },
    {
      "title": "5. Device Types & Capabilities",
      "content": "<p>What kind of device the kernel and user space think you are is decided entirely by the <strong>capability bits</strong> you set. Get these right and libinput/X classify the device correctly.</p><h4>Relative vs absolute</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">Device</th><th style=\"text-align:left; padding:0.5rem;\">Event type</th><th style=\"text-align:left; padding:0.5rem;\">Reports</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Keyboard / button</td><td style=\"padding:0.5rem;\"><code>EV_KEY</code></td><td style=\"padding:0.5rem;\">key up/down</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Mouse</td><td style=\"padding:0.5rem;\"><code>EV_REL</code></td><td style=\"padding:0.5rem;\">deltas (REL_X/Y/WHEEL)</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Touchscreen / tablet</td><td style=\"padding:0.5rem;\"><code>EV_ABS</code></td><td style=\"padding:0.5rem;\">absolute coords (ABS_X/Y)</td></tr><tr><td style=\"padding:0.5rem;\">Joystick</td><td style=\"padding:0.5rem;\"><code>EV_ABS</code>+<code>EV_KEY</code></td><td style=\"padding:0.5rem;\">axes + buttons</td></tr></table><h4>Absolute axes need range parameters</h4><pre><code>// A touchscreen must announce the coordinate RANGE so user space can scale:\ninput_set_capability(ts_dev, EV_ABS, ABS_X);\ninput_set_capability(ts_dev, EV_ABS, ABS_Y);\ninput_set_abs_params(ts_dev, ABS_X, 0, 1023, 0 /*fuzz*/, 0 /*flat*/);\ninput_set_abs_params(ts_dev, ABS_Y, 0, 767, 0, 0);\n//   min .. max define the raw coordinate range the controller reports;\n//   fuzz filters jitter, flat is a deadzone (useful for joysticks).</code></pre><h4>Multitouch (MT protocol, brief)</h4><pre><code>// Modern touchscreens report multiple contacts via the MT protocol:\n//   ABS_MT_SLOT, ABS_MT_TRACKING_ID, ABS_MT_POSITION_X/Y\n// The input_mt_* helpers manage slots; input_mt_sync_frame()/input_sync()\n// close each frame. Report per-contact, then sync once.</code></pre><h4>Autorepeat</h4><pre><code>// Let the input core auto-generate repeat events for held keys:\nset_bit(EV_REP, dev->evbit);\n// The core then emits value=2 (autorepeat) while a key is held -- you don't\n// have to time it yourself. Tunable via /sys and the REP_DELAY/REP_PERIOD.</code></pre>"
    },
    {
      "title": "6. evdev & the /dev/input Interface",
      "content": "<p><strong>evdev</strong> is the generic input handler that exposes each device as <code>/dev/input/eventX</code>. User space reads fixed-size <code>struct input_event</code> records from it.</p><h4>The device nodes</h4><pre><code>ls /dev/input/\n#   event0  event1  ...  mice  mouse0\nls -l /dev/input/by-id/     # stable symlinks by device identity\nls -l /dev/input/by-path/   # stable symlinks by physical port\n# Prefer by-id/by-path in scripts -- eventX numbers can change across boots.</code></pre><h4>Read-side flow</h4><pre><code>app: open(\"/dev/input/event3\")  ── (usually needs the 'input' group / root)\n   │\n   ▼\napp: read(fd, &ev, sizeof(ev))  ── blocks until an event is available\n   │\n   ▼\nevdev copies the next struct input_event out of its per-open buffer\n   │\n   ▼\napp handles ev.type/ev.code/ev.value; on EV_SYN it has a COMPLETE packet</code></pre><h4>Reading events in C</h4><pre><code>#include <linux/input.h>\n#include <fcntl.h>\n#include <unistd.h>\n\nint fd = open(\"/dev/input/event3\", O_RDONLY);\nstruct input_event ev;\n\nwhile (read(fd, &ev, sizeof(ev)) == sizeof(ev)) {\n    if (ev.type == EV_KEY)\n        printf(\"key %u %s\\n\", ev.code,\n               ev.value == 1 ? \"pressed\" :\n               ev.value == 0 ? \"released\" : \"repeat\");\n    else if (ev.type == EV_REL)\n        printf(\"rel axis %u delta %d\\n\", ev.code, ev.value);\n    else if (ev.type == EV_SYN)\n        printf(\"--- end of packet ---\\n\");\n}\nclose(fd);\n// For many devices at once, use poll()/epoll() on several event fds\n// (see the io_uring topic for scalable readiness notification).</code></pre>"
    },
    {
      "title": "7. User-Space Tools & the Stack",
      "content": "<h4>Inspecting input devices</h4><pre><code>cat /proc/bus/input/devices     # every input device: name, capabilities, evX\n#   I: Bus=... Vendor=... Product=...\n#   N: Name=\"GPIO Button\"\n#   H: Handlers=kbd event3        <- maps to /dev/input/event3\n#   B: EV=...  B: KEY=...          <- the capability bitmasks\n\nls /sys/class/input/             # sysfs view of input devices/handlers\nlibinput list-devices            # high-level: what libinput sees\nlsinput                          # (input-utils) list devices + capabilities</code></pre><h4>Watching events live</h4><pre><code>sudo evtest /dev/input/event3    # THE tool: prints every event as it arrives\nsudo evtest                       # menu of devices, then live events\n#   Event: type 1 (EV_KEY), code 28 (KEY_ENTER), value 1\n#   Event: -------------- SYN_REPORT ------------\n\n# X11 devices:\nxinput list                       # X input devices\nxinput test <id>                  # events for one device (X only)</code></pre><h4>Where it plugs into the desktop</h4><pre><code>evdev (/dev/input/eventX)\n   │\n   ▼\nlibinput          ── gesture/accel/palm-rejection processing\n   │\n   ├──► Wayland compositor  (sends input to clients)\n   └──► X.Org (xf86-input-libinput)\n#\n# On a server/embedded box there may be no libinput/X at all -- your program\n# can read /dev/input/eventX directly. (Desktop notifications/config often\n# ride D-Bus -- see the D-Bus topic.)</code></pre><h4>Permissions</h4><pre><code># /dev/input/event* is typically root:input, mode 0640.\nsudo usermod -aG input $USER      # read input devices without sudo (re-login)\n# udev rules under /lib/udev/rules.d set these; add your own if needed.</code></pre>"
    },
    {
      "title": "8. Debugging & References",
      "content": "<h4>Is my device there, and does it advertise the right bits?</h4><pre><code>cat /proc/bus/input/devices | grep -A6 \"GPIO Button\"\n#   check the Handlers= line has 'eventN' and the B: (bitmap) lines list\n#   the EV_KEY/KEY_* (or EV_ABS/ABS_*) you set -- if a capability bit is\n#   missing, you forgot to declare it before input_register_device().\n\ndmesg | grep -i input             # registration messages / errors\nsudo evtest /dev/input/eventN     # confirm events actually flow</code></pre><h4>Common problems</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">Symptom</th><th style=\"text-align:left; padding:0.5rem;\">Cause</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Events never reach user space</td><td style=\"padding:0.5rem;\">Missing <code>input_sync()</code> after reporting</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Key/axis ignored</td><td style=\"padding:0.5rem;\">Capability bit not declared before register</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Touchscreen coords wrong/clamped</td><td style=\"padding:0.5rem;\">Bad <code>input_set_abs_params</code> min/max</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Only press OR release seen</td><td style=\"padding:0.5rem;\">IRQ on a single edge (need both edges)</td></tr><tr><td style=\"padding:0.5rem;\">Permission denied on eventX</td><td style=\"padding:0.5rem;\">User not in the <code>input</code> group</td></tr></table><h4>Key takeaways</h4><ul><li>Implement only the <strong>device driver</strong>; the input core + evdev give you <code>/dev/input/eventX</code> and a stable event format.</li><li>Everything is <strong>type / code / value</strong>; group related events with <code>input_sync()</code> (SYN_REPORT).</li><li><strong>Declare capabilities</strong> before registering — that's how the device is classified.</li><li><code>evtest</code> + <code>/proc/bus/input/devices</code> are your first debugging stops.</li></ul><p><strong>References:</strong></p><ul><li><a href=\"https://docs.kernel.org/input/input-programming.html\" target=\"_blank\">Linux Kernel: Programming input drivers</a></li><li><a href=\"https://docs.kernel.org/input/event-codes.html\" target=\"_blank\">Linux Kernel: Input event codes (type/code/value)</a></li><li><a href=\"https://docs.kernel.org/input/multi-touch-protocol.html\" target=\"_blank\">Linux Kernel: Multi-touch (MT) protocol</a></li><li><a href=\"https://wayland.freedesktop.org/libinput/doc/latest/\" target=\"_blank\">libinput documentation</a></li><li><a href=\"https://lwn.net/Kernel/LDD3/\" target=\"_blank\">Linux Device Drivers, 3rd ed. (LDD3)</a></li></ul>"
    }
  ]
};
