/**
 * Topic: Process Management
 */
const TOPIC_PROCESS = {
  "id": "process",
  "category": "core",
  "icon": "⚙️",
  "title": "Process Management",
  "description": "Understand and control Linux processes — what a process is, states & attributes, monitoring, signals, job control, scheduling priorities, resource limits & cgroups, and scheduled execution",
  "keywords": [
    "process", "pid", "ppid", "thread", "fork", "exec", "ps", "top", "htop",
    "pgrep", "pidof", "pstree", "kill", "killall", "pkill", "signal",
    "sigterm", "sigkill", "zombie", "orphan", "job control", "nohup",
    "disown", "tmux", "screen", "nice", "renice", "priority", "chrt",
    "taskset", "affinity", "ulimit", "cgroup", "cgroups", "oom", "cron",
    "crontab", "systemd timer", "at", "proc"
  ],
  "sections": [
    {
      "title": "1. What is a Process?",
      "content": "<p>A <strong>program</strong> is a file on disk; a <strong>process</strong> is a running instance of it — with its own memory, open files, and a unique <strong>PID</strong> (process ID). Each process also records its <strong>PPID</strong> (parent's PID), forming a tree rooted at PID 1 (<code>init</code>/<code>systemd</code>).</p><h4>Process vs thread</h4><pre><code># Process : independent address space, own PID, isolated from others.\n# Thread  : a unit of execution INSIDE a process, sharing its memory.\n#           On Linux, threads are \"tasks\" that share resources -- lightweight.\n#\n# One process can contain many threads (a browser tab, a worker pool, ...).</code></pre><h4>How processes are created (fork + exec)</h4><pre><code># Linux creates processes by DUPLICATING the caller (fork), then optionally\n# REPLACING the program image (exec):\n#\n#   parent ──fork()──► child (copy)\n#                        └─exec()─► runs a new program\n#\n# The shell does exactly this for every command you type.\n# (See the TLPI topic for the fork/exec/wait system-call detail.)</code></pre><h4>Process lifecycle</h4><pre><code>┌─────────┐ fork  ┌─────────┐ scheduled ┌──────────┐\n│ Created │ ────► │  Ready  │ ────────► │ Running  │\n└─────────┘       └─────────┘ ◄──────── └────┬─────┘\n                       ▲  preempted           │\n           wakes up    │                       │ waits for I/O / event\n                  ┌────┴─────┐                 ▼\n                  │ Sleeping │ ◄──────────────┘\n                  └──────────┘\n#\n# On exit, a process becomes a ZOMBIE until its parent reaps its exit status,\n# then it is removed. If the parent dies first, the child is an ORPHAN and is\n# adopted by PID 1.</code></pre>"
    },
    {
      "title": "2. Process States & /proc",
      "content": "<p>Every process is in one of several <strong>states</strong>, shown in the <code>STAT</code> column of <code>ps</code> or the <code>S</code> column of <code>top</code>.</p><h4>Process states</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">Code</th><th style=\"text-align:left; padding:0.5rem;\">State</th><th style=\"text-align:left; padding:0.5rem;\">Meaning</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>R</code></td><td style=\"padding:0.5rem;\">Running / runnable</td><td style=\"padding:0.5rem;\">On CPU or waiting for a CPU slot</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>S</code></td><td style=\"padding:0.5rem;\">Interruptible sleep</td><td style=\"padding:0.5rem;\">Waiting for an event (most idle procs)</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>D</code></td><td style=\"padding:0.5rem;\">Uninterruptible sleep</td><td style=\"padding:0.5rem;\">Blocked in the kernel (usually I/O) — can't be killed</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>T</code></td><td style=\"padding:0.5rem;\">Stopped</td><td style=\"padding:0.5rem;\">Suspended (Ctrl-Z or SIGSTOP)</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>Z</code></td><td style=\"padding:0.5rem;\">Zombie</td><td style=\"padding:0.5rem;\">Finished, waiting for parent to reap it</td></tr></table><h4>The D state and zombies</h4><pre><code># A process stuck in D (uninterruptible sleep) is blocked on hardware/I/O --\n# even 'kill -9' won't remove it until the I/O completes or times out.\n# Persistent D often means a hung disk / NFS mount (see hw-diagnostics).\n\n# A ZOMBIE (Z) has already exited; it holds no memory, just an exit-status\n# slot. Many zombies = a buggy parent not calling wait(). Fix the parent\n# (or kill it, so PID 1 reaps the children).\nps aux | awk '$8 ~ /Z/ {print}'      # list zombies</code></pre><h4>Reading a process via /proc</h4><pre><code># Each process exposes a live directory under /proc/<pid>/ :\ncat /proc/1234/status        # state, memory, UID, threads, signals\ncat /proc/1234/cmdline | tr '\\0' ' '   # exact command line (NUL-separated)\nls -l /proc/1234/fd          # open file descriptors (and what they point to)\ncat /proc/1234/maps          # memory map (loaded libs, stack, heap)\nreadlink /proc/1234/exe      # path to the running binary\nreadlink /proc/1234/cwd      # current working directory</code></pre>"
    },
    {
      "title": "3. Monitoring Processes",
      "content": "<h4>ps — snapshot of processes</h4><pre><code>ps aux                       # BSD syntax: ALL processes, user + %CPU/%MEM\nps -ef                       # standard syntax: full listing with PPID\n\n# Custom columns, sorted by memory then CPU:\nps -eo pid,ppid,user,%cpu,%mem,stat,comm --sort=-%mem | head\n\n# Just one program:\nps -C nginx -o pid,%cpu,%mem,rss,cmd</code></pre><h4>top / htop — live view</h4><pre><code>top                          # live; press: P=sort by CPU, M=by memory,\n                             #             k=kill, r=renice, q=quit\ntop -p 1234                  # watch a single PID\nhtop                         # friendlier: scroll, mouse, tree view (F5),\n                             #             filter (F4), kill (F9)</code></pre><h4>Finding processes</h4><pre><code>pgrep -a nginx               # PIDs (and cmdline) matching a name\npgrep -u alice               # processes owned by a user\npidof sshd                   # PID(s) of an exact program\npstree -p                    # the whole tree with PIDs\npstree -p 1234               # subtree under one PID\n\n# What is using a file / port / directory?\nlsof /var/log/syslog         # processes with this file open\nlsof -i :8080                # processes listening on/using port 8080\nfuser -v /mnt/data           # processes using a mount point</code></pre>"
    },
    {
      "title": "4. Signals & Process Control",
      "content": "<p>You control processes by sending them <strong>signals</strong> — asynchronous notifications the process can catch, ignore, or be terminated by.</p><h4>Common signals</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">Signal</th><th style=\"text-align:left; padding:0.5rem;\">Number</th><th style=\"text-align:left; padding:0.5rem;\">Effect</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>SIGTERM</code></td><td style=\"padding:0.5rem;\">15</td><td style=\"padding:0.5rem;\">Polite \"please stop\" (default; catchable)</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>SIGKILL</code></td><td style=\"padding:0.5rem;\">9</td><td style=\"padding:0.5rem;\">Force kill — cannot be caught or ignored</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>SIGINT</code></td><td style=\"padding:0.5rem;\">2</td><td style=\"padding:0.5rem;\">Interrupt from keyboard (Ctrl-C)</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>SIGHUP</code></td><td style=\"padding:0.5rem;\">1</td><td style=\"padding:0.5rem;\">Terminal closed / reload config (daemons)</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>SIGSTOP</code></td><td style=\"padding:0.5rem;\">19</td><td style=\"padding:0.5rem;\">Suspend — cannot be caught</td></tr><tr><td style=\"padding:0.5rem;\"><code>SIGCONT</code></td><td style=\"padding:0.5rem;\">18</td><td style=\"padding:0.5rem;\">Resume a stopped process</td></tr></table><h4>Sending signals</h4><pre><code>kill 1234                    # send SIGTERM (15) -- the polite default\nkill -9 1234                 # SIGKILL -- last resort, no cleanup\nkill -HUP 1234               # by name; e.g. tell a daemon to reload config\nkill -l                      # list all signal names/numbers\n\nkillall nginx                # signal all processes named 'nginx'\npkill -u alice firefox       # match by name + owner\npkill -f \"python .*worker\"   # match against the FULL command line\n\n# Always try SIGTERM first (lets the process flush/clean up); use SIGKILL\n# only if it won't exit. SIGKILL/SIGSTOP are the two signals a process can\n# never intercept.</code></pre><h4>Escalation pattern</h4><pre><code>kill 1234 ; sleep 5 ; kill -9 1234 2>/dev/null   # TERM, then KILL if alive</code></pre>"
    },
    {
      "title": "5. Job Control & Background Execution",
      "content": "<p>The shell manages the commands you launch as <strong>jobs</strong>, letting you run things in the background and detach long-running work.</p><h4>Foreground / background / suspend</h4><pre><code>command &                    # start in the background\nCtrl+Z                       # suspend the foreground job (state T)\nbg                           # resume the suspended job in the background\nfg                           # bring a background job to the foreground\njobs -l                      # list this shell's jobs (with PIDs)\nfg %1                        # foreground job number 1\nkill %2                      # signal job number 2</code></pre><h4>Surviving a closed terminal</h4><pre><code># When a terminal closes, its shell sends SIGHUP to child jobs. To keep a\n# process running after logout:\n\nnohup ./long-task.sh &       # ignore SIGHUP; output -> nohup.out\n./task.sh & disown           # detach an already-running job from the shell\nsetsid ./task.sh             # start in a new session, fully detached</code></pre><h4>Persistent sessions: tmux / screen</h4><pre><code># For interactive work you want to reconnect to (remote builds, monitoring),\n# a terminal multiplexer is better than nohup:\ntmux new -s work             # start a named session\n#   ... run things ...   detach with  Ctrl-b  d\ntmux attach -t work          # reattach later (even after SSH dropped)\ntmux ls                      # list sessions\n\nscreen -S work               # the older equivalent; detach Ctrl-a d,\nscreen -r work               # reattach</code></pre>"
    },
    {
      "title": "6. Priorities, Scheduling & Affinity",
      "content": "<p>The kernel scheduler decides which runnable process gets the CPU. You can bias those decisions with <strong>niceness</strong>, real-time policies, and CPU affinity.</p><h4>Niceness (nice value)</h4><pre><code># Nice ranges -20 (highest priority) .. +19 (lowest). Higher nice = \"nicer\"\n# to others = less CPU. Normal users can only RAISE niceness (lower priority).\n\nnice -n 10 ./batch-job.sh    # start a job at lower priority\nrenice -n 5 -p 1234          # change a running process's niceness\nrenice -n -5 -p 1234         # raise priority (needs root)\nps -eo pid,ni,comm --sort=ni # view niceness of all processes</code></pre><h4>Real-time scheduling policies</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">Policy</th><th style=\"text-align:left; padding:0.5rem;\">Behavior</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>SCHED_OTHER</code></td><td style=\"padding:0.5rem;\">Default time-sharing (governed by the fair scheduler)</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>SCHED_FIFO</code></td><td style=\"padding:0.5rem;\">Real-time, runs until it blocks/yields</td></tr><tr><td style=\"padding:0.5rem;\"><code>SCHED_RR</code></td><td style=\"padding:0.5rem;\">Real-time round-robin with time slices</td></tr></table><pre><code>chrt -f 50 ./rt-task         # run with SCHED_FIFO priority 50 (needs root)\nchrt -p 1234                 # show a process's policy &amp; priority\n\n# (For how normal SCHED_OTHER tasks are scheduled, see the EEVDF topic.)</code></pre><h4>CPU affinity — pin to specific cores</h4><pre><code>taskset -c 0,1 ./task        # run only on CPU cores 0 and 1\ntaskset -pc 2-3 1234         # move running PID 1234 onto cores 2-3\ntaskset -pc 1234             # show a process's current affinity mask\n# Pinning improves cache locality for latency-sensitive workloads.</code></pre>"
    },
    {
      "title": "7. Resource Limits & cgroups",
      "content": "<p>Two mechanisms bound how much a process can consume: per-process <strong>ulimits</strong> and per-group <strong>cgroups</strong>.</p><h4>ulimit — per-process limits</h4><pre><code>ulimit -a                    # show all current limits\nulimit -n                    # max open file descriptors (soft limit)\nulimit -n 4096               # raise it for THIS shell + its children\nulimit -u                    # max user processes (guards against fork bombs)\nulimit -c unlimited          # allow core dumps for debugging\n\n# Soft limit = current cap (user-adjustable up to the hard limit).\n# Hard limit = ceiling (only root can raise). Persistent defaults live in:\n/etc/security/limits.conf    # e.g.  alice  hard  nofile  65535</code></pre><h4>cgroups v2 — group resource control</h4><pre><code># Control groups cap CPU / memory / I/O for a WHOLE group of processes.\n# This is how systemd services and containers are constrained.\n\nsystemctl status nginx       # shows the service's cgroup + resource use\nsystemd-cgtop                # live per-cgroup CPU/memory/IO (like top)\nsystemd-cgls                 # the cgroup hierarchy as a tree\n\n# Cap a systemd service's resources:\nsudo systemctl set-property nginx.service MemoryMax=512M CPUQuota=50%\n\n# Run a one-off command inside a limited transient scope:\nsystemd-run --scope -p MemoryMax=200M -p CPUQuota=25% ./heavy-job\n\n# The raw interface lives under /sys/fs/cgroup/ (v2 unified hierarchy).</code></pre><h4>The OOM killer</h4><pre><code># When memory is exhausted, the kernel's Out-Of-Memory killer terminates a\n# process to recover. Check what got killed:\ndmesg | grep -i \"killed process\"\njournalctl -k | grep -i oom\n\n# Bias the choice per process (higher = more likely to be killed, -1000..1000):\necho -500 | sudo tee /proc/1234/oom_score_adj\ncat /proc/1234/oom_score      # the current badness score</code></pre>"
    },
    {
      "title": "8. Scheduled & Managed Execution",
      "content": "<h4>cron — recurring jobs</h4><pre><code>crontab -e                   # edit YOUR user crontab\ncrontab -l                   # list it\n\n# Format:  minute hour day-of-month month day-of-week  command\n#          (0-59) (0-23) (1-31)    (1-12) (0-7, 0/7=Sun)\n0 2 * * *   /usr/local/bin/backup.sh     # daily at 02:00\n*/5 * * * * /scripts/health-check.sh     # every 5 minutes\n0 9 * * 1   /scripts/weekly-report.sh    # Mondays at 09:00\n@reboot     /scripts/startup.sh          # once at boot</code></pre><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">Location</th><th style=\"text-align:left; padding:0.5rem;\">Use</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>crontab -e</code></td><td style=\"padding:0.5rem;\">Per-user jobs</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>/etc/crontab</code>, <code>/etc/cron.d/</code></td><td style=\"padding:0.5rem;\">System jobs (include a user field)</td></tr><tr><td style=\"padding:0.5rem;\"><code>/etc/cron.{daily,weekly}/</code></td><td style=\"padding:0.5rem;\">Drop-in scripts run periodically</td></tr></table><h4>systemd timers — the modern alternative</h4><pre><code># Timers integrate with the journal, support randomized delays, catch up on\n# missed runs, and show clear status. A timer + service pair:\n\n# /etc/systemd/system/backup.service   (what to run)\n#   [Service]\n#   ExecStart=/usr/local/bin/backup.sh\n\n# /etc/systemd/system/backup.timer     (when to run)\n#   [Timer]\n#   OnCalendar=*-*-* 02:00:00\n#   Persistent=true\n\nsudo systemctl enable --now backup.timer\nsystemctl list-timers        # all timers + next/last run\njournalctl -u backup.service # its logs</code></pre><h4>at — one-off future jobs</h4><pre><code>echo \"/scripts/notify.sh\" | at 22:00        # run once at 22:00 today\nat now + 1 hour              # interactive one-off scheduling\natq                          # list pending at jobs\natrm 3                       # remove at job 3</code></pre><p><strong>References:</strong></p><ul><li><a href=\"https://man7.org/linux/man-pages/man1/ps.1.html\" target=\"_blank\">ps(1) — man page</a></li><li><a href=\"https://man7.org/linux/man-pages/man7/signal.7.html\" target=\"_blank\">signal(7) — overview of signals</a></li><li><a href=\"https://docs.kernel.org/admin-guide/cgroup-v2.html\" target=\"_blank\">Linux Kernel: Control Group v2</a></li><li><a href=\"https://man7.org/linux/man-pages/man5/proc.5.html\" target=\"_blank\">proc(5) — the /proc filesystem</a></li><li><a href=\"https://man7.org/linux/man-pages/man5/systemd.timer.5.html\" target=\"_blank\">systemd.timer(5) — man page</a></li></ul>"
    }
  ]
};
