/**
 * Topic: C Programming
 */
const TOPIC_C_LANG = {
  "id": "c-lang",
  "category": "languages",
  "icon": "🔧",
  "title": "C Programming",
  "description": "C for Linux systems programming — the compilation pipeline, types & control flow, pointers & memory, structs/strings, the preprocessor, POSIX system calls, undefined behavior, and debugging, with flow charts",
  "keywords": [
    "c", "c programming", "gcc", "clang", "pointer", "memory", "malloc",
    "free", "compilation", "preprocessor", "macro", "struct", "union",
    "enum", "bitfield", "string", "char", "pthread", "posix", "syscall",
    "undefined behavior", "ub", "segfault", "valgrind", "asan", "gdb",
    "makefile", "cmake", "linker", "static", "volatile", "const", "sizeof"
  ],
  "sections": [
    {
      "title": "1. Why C & the Compilation Pipeline",
      "content": "<h4>Why C for Linux?</h4><ul><li>The Linux kernel is written in C (~30M lines) — knowing C is knowing Linux from the inside.</li><li>Direct hardware access: pointers, bitwise ops, <code>volatile</code>, memory-mapped I/O.</li><li>Zero runtime overhead — no garbage collector, no VM.</li><li>The POSIX API and almost every system interface is C-native.</li></ul><h4>The compilation pipeline (source → executable)</h4><pre><code>  main.c\n    │\n    ▼  1. PREPROCESS  (cpp): expand #include, #define, #ifdef\n  main.i   (pure C, macros expanded, headers pasted in)\n    │\n    ▼  2. COMPILE  (cc1): C -> assembly, optimize\n  main.s   (assembly for this CPU)\n    │\n    ▼  3. ASSEMBLE  (as): assembly -> machine code\n  main.o   (object file: machine code + unresolved symbols)\n    │\n    ▼  4. LINK  (ld): combine .o files + libraries, resolve symbols\n  a.out    (executable)\n#\n# 'gcc' drives all four stages. Errors tell you WHICH stage failed:\n#   'undefined reference to foo' = LINK error (missing .o or -l library)\n#   'implicit declaration of foo' = COMPILE (missing #include / prototype)</code></pre><h4>Driving the toolchain</h4><pre><code>gcc -Wall -Wextra -O2 -o app main.c        # all-in-one (compile + link)\n\ngcc -E main.c -o main.i                    # stop after preprocess\ngcc -S main.c -o main.s                    # stop after compile (see the asm)\ngcc -c main.c -o main.o                    # compile+assemble only (no link)\ngcc -o app main.o util.o -lpthread -lm     # link objects + libraries\n\ngcc -g -O0 main.c -o app_dbg               # debug build (symbols, no opt)\ngcc -fsanitize=address,undefined main.c    # instrument for runtime checks\ncppcheck --enable=all main.c ; gcc -fanalyzer main.c   # static analysis</code></pre><h4>C standards</h4><pre><code>gcc -std=c11 ...     # C99 / C11 / C17 / C23. -std=gnu11 adds GNU extensions.\n# The kernel uses a specific GNU C dialect; userspace commonly targets c11/c17.</code></pre>"
    },
    {
      "title": "2. Types, Operators & Control Flow",
      "content": "<h4>Fundamental types & fixed-width integers</h4><pre><code>#include <stdint.h>   // portable, exact-width types -- PREFER these\nint8_t / uint8_t   int16_t   int32_t   int64_t   // exact sizes\nsize_t             // unsigned; the type of sizeof and object sizes\nssize_t            // signed size (read/write return this)\nintptr_t           // an integer big enough to hold a pointer\nbool               // <stdbool.h>\n\n// 'int' etc. have platform-dependent sizes; use sizeof, never assume:\nprintf(\"%zu\\n\", sizeof(long));    // %zu for size_t; 8 on 64-bit Linux</code></pre><h4>Integer promotion &amp; overflow (a real hazard)</h4><pre><code># SIGNED overflow is UNDEFINED BEHAVIOR (see section 8); unsigned wraps.\nint a = INT_MAX; a + 1;            // UB -- optimizer may assume it can't happen\nunsigned u = 0; u - 1;            // defined: wraps to UINT_MAX\n\n# Mixing signed/unsigned converts the signed operand to unsigned -> surprises:\nint i = -1;\nif (i < sizeof(x)) ...            // -1 becomes a HUGE unsigned! bug.\n# Compile with -Wall -Wextra -Wsign-conversion to catch these.</code></pre><h4>Bitwise operations (essential for systems)</h4><pre><code>flags |=  (1u << 3);   // SET bit 3\nflags &= ~(1u << 3);   // CLEAR bit 3\nflags ^=  (1u << 3);   // TOGGLE bit 3\nif (flags & (1u << 3)) // TEST bit 3\nval = (reg >> 4) & 0xF; // extract a 4-bit field\n// &amp; | ^ ~ &lt;&lt; &gt;&gt; -- used constantly for registers, masks, protocols.</code></pre><h4>Control flow &amp; storage qualifiers</h4><pre><code>if/else, while, do..while, for, switch(x){ case 1: ...; break; default: }\n\nconst int   MAX = 100;   // read-only (compiler enforces)\nstatic int  counter;     // file/function scope; persists; internal linkage\nvolatile u32 *reg;       // never cache/optimize accesses (MMIO, signals)\nregister int i;          // hint (largely ignored by modern compilers)\n\n# 'const' catches accidental writes; 'volatile' is REQUIRED for memory-mapped\n# registers and variables shared with signal handlers/interrupts.</code></pre>"
    },
    {
      "title": "3. Pointers & Memory Management",
      "content": "<h4>Pointers &amp; arithmetic</h4><pre><code>int arr[5] = {10,20,30,40,50};\nint *p = arr;              // array decays to pointer to first element\n*(p + 2)  ==  p[2]  ==  30;   // pointer arithmetic in ELEMENT units\n\nvoid *generic = malloc(100);       // void* = untyped; cast to use\nint  *typed   = generic;\n\n// Function pointer (dispatch tables, callbacks like qsort):\nint (*cmp)(const void *, const void *) = compare_ints;\nqsort(arr, 5, sizeof(int), cmp);\n\nint **pp = &p;             // pointer to pointer\nconst char *s = \"hi\";      // pointer to read-only chars</code></pre><h4>A process's memory layout</h4><pre><code>  high addresses\n  ┌───────────────────┐\n  │   command-line args / env         │\n  ├───────────────────┤\n  │   STACK   ↓ grows down             │  locals, call frames (auto storage)\n  │        ...                          │\n  │   HEAP    ↑ grows up               │  malloc/free (dynamic)\n  ├───────────────────┤\n  │   BSS      uninitialized globals   │  zeroed at start\n  │   DATA     initialized globals     │\n  │   TEXT     code (read-only)        │  the program instructions\n  └───────────────────┘\n  low addresses\n#\n# Stack: automatic, freed on return -- NEVER return a pointer to a local.\n# Heap:  you own it -- every malloc needs exactly one free.</code></pre><h4>Dynamic memory</h4><pre><code>int *buf = malloc(n * sizeof *buf);   // 'sizeof *buf' style survives type changes\nif (!buf) { /* handle OOM */ }        // malloc CAN fail -- always check\nint *z   = calloc(n, sizeof *z);      // zero-initialized\nbuf = realloc(buf, 2*n * sizeof *buf);// grow/shrink (may move the block)\n\nfree(buf);\nbuf = NULL;                            // avoid a dangling pointer / double free</code></pre><h4>The classic memory bugs</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">Bug</th><th style=\"text-align:left; padding:0.5rem;\">Caught by</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Use-after-free / double free</td><td style=\"padding:0.5rem;\">ASan, valgrind</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Buffer overflow (write past end)</td><td style=\"padding:0.5rem;\">ASan, valgrind</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Memory leak (forgot free)</td><td style=\"padding:0.5rem;\">valgrind --leak-check=full</td></tr><tr><td style=\"padding:0.5rem;\">Uninitialized read</td><td style=\"padding:0.5rem;\">MSan, valgrind</td></tr></table><pre><code>gcc -fsanitize=address -g app.c        # ASan: fast, prints exact bug + stack\nvalgrind --leak-check=full ./app       # thorough leak/UAF detection</code></pre>"
    },
    {
      "title": "4. Structs, Unions, Enums & Strings",
      "content": "<h4>Structs &amp; memory layout (padding)</h4><pre><code>struct packet {\n    uint8_t  type;    // offset 0\n    // 3 bytes PADDING inserted here for alignment\n    uint32_t len;     // offset 4 (must be 4-byte aligned)\n    uint8_t  flags;   // offset 8\n};   // sizeof == 12, not 6 -- the compiler pads for alignment\n\n# Reorder members (largest first) to shrink structs. For wire/HW formats where\n# layout must be exact, use __attribute__((packed)) -- but packed access can\n# be slower / unaligned. Check with:  offsetof(struct packet, len);</code></pre><h4>Unions &amp; bitfields</h4><pre><code>union value {          // all members share the SAME storage\n    uint32_t u;\n    float    f;\n    uint8_t  bytes[4];\n};   // sizeof == 4 (the largest member); read what you wrote\n\nstruct reg {           // bitfields: pack flags into specific bits\n    unsigned enable : 1;\n    unsigned mode   : 3;\n    unsigned rsvd   : 4;\n};   // handy for registers, but bit ORDER is implementation-defined</code></pre><h4>Enums &amp; typedef</h4><pre><code>enum state { IDLE, RUNNING, STOPPED };   // IDLE=0, RUNNING=1, ...\ntypedef struct node { int v; struct node *next; } node_t;   // name a type</code></pre><h4>C strings — a byte array ending in '\\0'</h4><pre><code>char s[] = \"hi\";     // {'h','i','\\0'} -- length 2, SIZE 3\nstrlen(s);           // 2 (walks to the '\\0'; O(n))\n\n// Safe-ish copying (always leave room for '\\0'):\nchar dst[8];\nstrncpy(dst, src, sizeof dst - 1); dst[sizeof dst - 1] = '\\0';\nsnprintf(dst, sizeof dst, \"%s-%d\", name, n);   // PREFER snprintf: bounded\n\n// The dangerous ones -- avoid on untrusted input:\n//   strcpy, strcat, sprintf, gets   (no bounds -> buffer overflow)\nmemcpy(dst, src, n);   // raw bytes; memmove if regions overlap; memset to fill</code></pre>"
    },
    {
      "title": "5. The Preprocessor & Multi-file Programs",
      "content": "<p>The preprocessor runs <em>before</em> compilation (stage 1 of section 1): it's pure text substitution. Real programs are split across many <strong>translation units</strong> (.c files) sharing declarations via headers.</p><h4>Macros</h4><pre><code>#define MAX_LEN 256                  // object-like constant\n#define SQ(x) ((x) * (x))            // function-like -- PARENTHESIZE everything\nSQ(a + 1)  ->  ((a + 1) * (a + 1))   // ...or 'a + 1 * a + 1' would be wrong!\n\n#define STR(x)  #x                   // # = stringify:  STR(hi) -> \"hi\"\n#define CAT(a,b) a##b                // ## = token paste: CAT(foo,bar) -> foobar\n\n#ifdef DEBUG                         // conditional compilation\n  #define DBG(...) fprintf(stderr, __VA_ARGS__)\n#else\n  #define DBG(...) ((void)0)\n#endif\n# Prefer const/enum/inline over macros when possible -- macros have no scope\n# or type checking and can bite (double evaluation: SQ(i++)).</code></pre><h4>Headers, guards &amp; linkage</h4><pre><code>// util.h -- DECLARATIONS shared across files\n#ifndef UTIL_H\n#define UTIL_H                       // include guard: prevents double-inclusion\nint add(int a, int b);               // prototype (declaration)\nextern int g_count;                  // declared here, DEFINED in one .c\n#endif\n\n// util.c -- DEFINITIONS\n#include \"util.h\"\nint g_count = 0;                     // the single definition\nint add(int a, int b) { return a + b; }\nstatic int helper(void) { ... }      // 'static' = INTERNAL linkage (file-local)</code></pre><h4>How the files fit together</h4><pre><code>  util.h  ────#include────┐        (declarations only)\n     │                     ▼\n  main.c ──compile──► main.o ─┐\n                              ├──LINK──► app\n  util.c ──compile──► util.o ─┘\n#\n# Each .c compiles INDEPENDENTLY into a .o (it only needs the .h prototypes).\n# The linker resolves calls between them. A missing definition -> 'undefined\n# reference'; two definitions of the same global -> 'multiple definition'.\n# 'static' functions/globals stay private to their .c (no clashes).</code></pre>"
    },
    {
      "title": "6. System Programming (POSIX)",
      "content": "<p>C is the native language of the Linux system-call interface. (For the full API — processes, signals, IPC, sockets — see the <strong>The Linux Programming Interface</strong> topic; here are the C essentials.)</p><h4>Low-level file I/O</h4><pre><code>#include <fcntl.h>\n#include <unistd.h>\n\nint fd = open(\"/etc/hostname\", O_RDONLY);\nif (fd == -1) { perror(\"open\"); return 1; }   // ALWAYS check\nchar buf[4096];\nssize_t n = read(fd, buf, sizeof buf);         // 0 = EOF, -1 = error\nwrite(STDOUT_FILENO, buf, n);\nclose(fd);\n\n// Direct/aligned I/O and mmap:\n#include <sys/mman.h>\nvoid *map = mmap(NULL, len, PROT_READ, MAP_PRIVATE, fd, 0);\n/* use map[0..len-1] */  munmap(map, len);</code></pre><h4>Threads (pthreads)</h4><pre><code>#include <pthread.h>\nvoid *worker(void *arg) { long id = (long)arg; /* ... */ return NULL; }\n\npthread_t t[4];\nfor (long i = 0; i < 4; i++) pthread_create(&t[i], NULL, worker, (void*)i);\nfor (int i = 0; i < 4; i++)  pthread_join(t[i], NULL);\n\n// Shared data needs a mutex:\npthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER;\npthread_mutex_lock(&m);  /* critical section */  pthread_mutex_unlock(&m);\n// Compile with -pthread.</code></pre><h4>Signals &amp; errno</h4><pre><code>#include <signal.h>\n#include <errno.h>\n#include <string.h>\n\nvolatile sig_atomic_t stop = 0;\nvoid on_int(int sig) { stop = 1; }        // handlers: keep tiny, set a flag\nstruct sigaction sa = { .sa_handler = on_int };\nsigaction(SIGINT, &sa, NULL);             // prefer sigaction over signal()\n\n// The error convention: -1 + errno\nif (open(\"/missing\", O_RDONLY) == -1)\n    fprintf(stderr, \"open: %s\\n\", strerror(errno));   // or perror(\"open\")</code></pre>"
    },
    {
      "title": "7. Data Structures & Kernel Idioms",
      "content": "<h4>Intrusive linked list (Linux kernel style)</h4><pre><code>// The list node is EMBEDDED in your struct -- no separate node allocation.\nstruct list_head { struct list_head *next, *prev; };\n\nstruct my_entry {\n    int data;\n    struct list_head list;    // embedded node\n};\n\n// container_of: recover the enclosing struct from a member pointer.\n#define container_of(ptr, type, member) \\\n    ((type *)((char *)(ptr) - offsetof(type, member)))\n\nstruct list_head *pos;\nlist_for_each(pos, &head) {\n    struct my_entry *e = container_of(pos, struct my_entry, list);\n    printf(\"%d\\n\", e->data);\n}\n# This pattern is EVERYWHERE in the kernel (see the driver topics + kernel-rcu).</code></pre><h4>Generic containers via void*</h4><pre><code>// C has no generics; you erase types with void* + a size/compare callback\n// (exactly how qsort/bsearch work):\nvoid *stack_pop(struct stack *s);           // returns void*\nqsort(arr, n, sizeof arr[0], compare_fn);   // sort anything</code></pre><h4>Hash table (uthash — header-only)</h4><pre><code>#include \"uthash.h\"\nstruct user { int id; char name[64]; UT_hash_handle hh; };\nstruct user *users = NULL;\n\nstruct user *u = malloc(sizeof *u);\nu->id = 42; strcpy(u->name, \"Alice\");\nHASH_ADD_INT(users, id, u);                 // add\n\nint key = 42; struct user *found;\nHASH_FIND_INT(users, &key, found);          // lookup\n# uthash makes any struct hashable by embedding a UT_hash_handle.</code></pre><h4>Kernel modules — a note</h4><pre><code># C is also the language of kernel modules. The MODULE skeleton\n# (module_init/exit, MODULE_LICENSE) and the build Makefile are covered in\n# depth in the CHARACTER DRIVERS topic -- and the whole Device Drivers\n# category builds on the same C foundations shown here.</code></pre>"
    },
    {
      "title": "8. Undefined Behavior & Robust C",
      "content": "<p>C's power comes with sharp edges: <strong>undefined behavior (UB)</strong>. When a program does something the standard leaves undefined, the compiler may do <em>anything</em> — often optimizing based on the assumption that UB never happens. Understanding UB is what separates fragile C from robust C.</p><h4>Common undefined behaviors</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">UB</th><th style=\"text-align:left; padding:0.5rem;\">Example</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Signed integer overflow</td><td style=\"padding:0.5rem;\"><code>INT_MAX + 1</code></td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Out-of-bounds access</td><td style=\"padding:0.5rem;\"><code>arr[n]</code> where n == length</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Use-after-free / dangling</td><td style=\"padding:0.5rem;\">using memory after <code>free</code></td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Reading uninitialized memory</td><td style=\"padding:0.5rem;\">using a local before assigning</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">NULL dereference</td><td style=\"padding:0.5rem;\"><code>*p</code> when p == NULL</td></tr><tr><td style=\"padding:0.5rem;\">Strict-aliasing violation</td><td style=\"padding:0.5rem;\">reading a float's bytes via <code>int*</code></td></tr></table><pre><code># Why it matters: the optimizer ASSUMES no UB. Classic example --\nif (ptr + off < ptr) { /* overflow check */ }   // UB: optimizer deletes this\n# -> your \"safety check\" vanishes. Check WITHOUT causing UB (compare offsets).</code></pre><h4>The goto-cleanup pattern (robust error handling)</h4><pre><code>int do_work(void) {\n    int ret = -1;\n    char *a = malloc(N);   if (!a) goto out;\n    char *b = malloc(M);   if (!b) goto free_a;\n    int fd = open(path, O_RDONLY); if (fd < 0) goto free_b;\n\n    /* ... real work ...; on success: */\n    ret = 0;\n\n    close(fd);\nfree_b: free(b);\nfree_a: free(a);\nout:    return ret;\n}\n# Single-exit cleanup in REVERSE acquisition order -- the standard kernel/\n# systems idiom for releasing resources on every path without duplication.</code></pre><h4>Catch UB automatically</h4><pre><code>gcc -fsanitize=undefined -g app.c   # UBSan: traps signed overflow, OOB, etc.\ngcc -fsanitize=address    -g app.c   # ASan: memory errors\ngcc -Wall -Wextra -Wpedantic -Werror # treat warnings as errors\n# Run the test suite under ASan+UBSan in CI -- most UB then shows up loudly.</code></pre>"
    },
    {
      "title": "9. Build, Debug & Profile",
      "content": "<h4>Makefile</h4><pre><code>CC      = gcc\nCFLAGS  = -Wall -Wextra -O2 -std=c11\nLDFLAGS = -pthread\nSRC = $(wildcard src/*.c)\nOBJ = $(SRC:.c=.o)\nTARGET = myapp\n\n$(TARGET): $(OBJ)\n\t$(CC) -o $@ $^ $(LDFLAGS)\n%.o: %.c\n\t$(CC) $(CFLAGS) -c -o $@ $<\nclean:\n\trm -f $(OBJ) $(TARGET)\n# (Tabs, not spaces, indent recipe lines. See the Shell topic for make basics.)</code></pre><h4>CMake (larger projects)</h4><pre><code># CMakeLists.txt\ncmake_minimum_required(VERSION 3.16)\nproject(myapp C)\nset(CMAKE_C_STANDARD 11)\nadd_executable(myapp src/main.c src/util.c)\ntarget_link_libraries(myapp pthread)\n# build:  cmake -B build && cmake --build build</code></pre><h4>Debugging &amp; profiling</h4><pre><code># gdb -- interactive debugger (build with -g -O0)\ngdb ./app\n  (gdb) break main       # set a breakpoint\n  (gdb) run              # start\n  (gdb) bt               # backtrace on a crash\n  (gdb) print var        # inspect a variable\n  (gdb) next / step / continue\n\n# valgrind -- memory errors + leaks (no rebuild needed)\nvalgrind --leak-check=full --track-origins=yes ./app\n\n# sanitizers -- best first line of defense (compile-time instrumentation)\ngcc -fsanitize=address,undefined -g app.c && ./a.out\n\n# strace -- see the syscalls the program makes (see the TLPI topic)\nstrace -f -e trace=openat,read,write ./app\n\n# perf -- sampling profiler: where is the CPU time going?\nperf record -g ./app && perf report</code></pre><h4>Best-practice checklist</h4><ul><li>Always build with <code>-Wall -Wextra</code>; run tests under <strong>ASan + UBSan</strong>.</li><li><strong>Check every</strong> <code>malloc</code>/<code>open</code>/<code>read</code>/<code>write</code> return value.</li><li>Free what you malloc; NULL the pointer; use the <strong>goto-cleanup</strong> pattern.</li><li>Use <code>const</code> for read-only, <code>size_t</code> for sizes, <code>snprintf</code> over <code>sprintf</code>.</li><li>Prefer fixed-width types (<code>&lt;stdint.h&gt;</code>) and avoid signed/unsigned mixing.</li></ul><p><strong>References:</strong></p><ul><li><a href=\"https://man7.org/linux/man-pages/\" target=\"_blank\">Linux man pages (sections 2 &amp; 3)</a></li><li><a href=\"https://docs.kernel.org/process/coding-style.html\" target=\"_blank\">Linux Kernel Coding Style</a></li><li><a href=\"https://beej.us/guide/bgc/\" target=\"_blank\">Beej's Guide to C Programming</a></li><li><a href=\"https://en.cppreference.com/w/c\" target=\"_blank\">cppreference — C library reference</a></li><li><a href=\"https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html\" target=\"_blank\">GCC sanitizer options</a></li></ul>"
    }
  ]
};
