/**
 * Topic: eBPF
 */
const TOPIC_EBPF = {
  "id": "ebpf",
  "icon": "🔬",
  "title": "eBPF",
  "description": "Learn eBPF — safely run custom programs in the kernel for observability, networking, and security",
  "sections": [
    {
      "title": "1. What is eBPF?",
      "content": "\n          <p><strong>eBPF (extended Berkeley Packet Filter)</strong> is a Linux kernel technology that allows running user-defined sandboxed programs in the kernel without modifying kernel source code or loading kernel modules.</p>\n          <p>Originally derived from packet filtering (BPF), it now extends far beyond networking into:</p>\n          <ul>\n            <li><strong>Observability</strong> — Trace syscalls, function latency, I/O behavior</li>\n            <li><strong>Networking</strong> — High-speed packet processing, load balancing (e.g., Cilium)</li>\n            <li><strong>Security</strong> — Runtime policy enforcement, anomaly detection (e.g., Falco, Tetragon)</li>\n            <li><strong>Profiling</strong> — CPU flamegraphs, memory tracing</li>\n          </ul>\n          <p>Reference: <a href=\"https://ebpf.io/\" target=\"_blank\">ebpf.io</a></p>\n        "
    },
    {
      "title": "2. Core Architecture & Principles",
      "content": "\n          <p>Lifecycle of an eBPF program:</p>\n          <ol>\n            <li><strong>Write</strong> — Author the eBPF program in restricted C</li>\n            <li><strong>Compile</strong> — Compile to eBPF bytecode via Clang/LLVM</li>\n            <li><strong>Verify</strong> — Kernel verifier ensures safety (no infinite loops, no out-of-bounds access, 512-byte stack limit)</li>\n            <li><strong>JIT Compile</strong> — Bytecode JIT-compiled to native machine code for near-zero overhead</li>\n            <li><strong>Attach</strong> — Attach to a designated hook point for execution</li>\n          </ol>\n          <h4>Hook Types</h4>\n          <ul>\n            <li><code>kprobe / kretprobe</code> — Kernel function entry/return</li>\n            <li><code>tracepoint</code> — Kernel static tracing points</li>\n            <li><code>uprobe / uretprobe</code> — Userspace function tracing</li>\n            <li><code>XDP (eXpress Data Path)</code> — Earliest packet processing at NIC driver level</li>\n            <li><code>TC (Traffic Control)</code> — Network traffic control layer</li>\n            <li><code>perf_event</code> — Hardware/software performance events</li>\n            <li><code>LSM (Linux Security Modules)</code> — Security policy hooks</li>\n          </ul>\n          <h4>Maps (Data Structures)</h4>\n          <p>eBPF Maps are shared data structures between kernel and userspace:</p>\n          <pre><code>Common Map types:\nBPF_MAP_TYPE_HASH         — Hash table\nBPF_MAP_TYPE_ARRAY        — Array\nBPF_MAP_TYPE_PERF_EVENT_ARRAY — Event buffer\nBPF_MAP_TYPE_RINGBUF      — High-performance ring buffer\nBPF_MAP_TYPE_LRU_HASH     — LRU-eviction hash table</code></pre>\n        "
    },
    {
      "title": "3. Development Environment Setup",
      "content": "\n          <p>Install the required tools for your distribution:</p>\n          <pre><code># === Ubuntu / Debian ===\nsudo apt update\nsudo apt install -y \\\n  bpfcc-tools libbpfcc-dev \\\n  linux-headers-$(uname -r) \\\n  bpftrace \\\n  clang llvm \\\n  libbpf-dev \\\n  python3-bpfcc\n\n# === RHEL / Fedora ===\nsudo dnf install -y \\\n  bcc bcc-tools bcc-devel \\\n  kernel-devel \\\n  bpftrace \\\n  clang llvm \\\n  libbpf-devel\n\n# === Verify installation ===\n# Ensure kernel version >= 4.15 (5.8+ recommended)\nuname -r\n\n# Test bpftrace\nsudo bpftrace -e 'BEGIN { printf(\"eBPF works!\\n\"); exit(); }'</code></pre>\n          <p><strong>Kernel version recommendations:</strong></p>\n          <ul>\n            <li>4.15+ — Basic eBPF support</li>\n            <li>5.3+ — BPF trampolines, bounded loops</li>\n            <li>5.8+ — ringbuf, full CO-RE BTF support</li>\n            <li>5.15+ — Full BTF for modules</li>\n          </ul>\n        "
    },
    {
      "title": "4. BCC Tools in Practice",
      "content": "\n          <p><a href=\"https://github.com/iovisor/bcc\" target=\"_blank\">BCC (BPF Compiler Collection)</a> provides many ready-to-use tracing tools:</p>\n          <pre><code># Trace process execution\nsudo execsnoop-bpfcc\n\n# Trace TCP connections\nsudo tcpconnect-bpfcc\n\n# Trace file opens\nsudo opensnoop-bpfcc\n\n# Trace block I/O latency\nsudo biolatency-bpfcc\n\n# Trace high-latency syscalls\nsudo syscount-bpfcc -L\n\n# Trace DNS lookups\nsudo gethostlatency-bpfcc\n\n# Profile CPU functions (generate flamegraph data)\nsudo profile-bpfcc -F 99 -p PID 10</code></pre>\n          <p><strong>bpftrace — One-liner tracing tool:</strong></p>\n          <pre><code># Count syscalls by process\nsudo bpftrace -e 'tracepoint:raw_syscalls:sys_enter { @[comm] = count(); }'\n\n# Trace open() syscall file names\nsudo bpftrace -e 'tracepoint:syscalls:sys_enter_openat { printf(\"%s %s\\n\", comm, str(args->filename)); }'\n\n# Histogram of VFS read sizes\nsudo bpftrace -e 'kprobe:vfs_read { @bytes = hist(arg2); }'\n\n# Trace process scheduling wakeups\nsudo bpftrace -e 'tracepoint:sched:sched_wakeup { @[comm] = count(); }'</code></pre>\n        "
    },
    {
      "title": "5. Writing Your First BCC Python Program",
      "content": "\n          <p>BCC provides a Python frontend for quickly writing custom eBPF programs:</p>\n          <pre><code>#!/usr/bin/env python3\n# hello_ebpf.py — Trace clone() syscall (new process creation)\nfrom bcc import BPF\n\n# eBPF program (C language)\nbpf_program = \"\"\"\nint hello_world(void *ctx) {\n    bpf_trace_printk(\"Hello eBPF! New process created\\\\n\");\n    return 0;\n}\n\"\"\"\n\n# Load and attach to clone syscall\nb = BPF(text=bpf_program)\nb.attach_kprobe(event=b.get_syscall_fnname(\"clone\"), fn_name=\"hello_world\")\n\nprint(\"Tracing new processes... Ctrl+C to exit\")\nb.trace_print()</code></pre>\n\n          <p><strong>Advanced example — Measuring syscall latency:</strong></p>\n          <pre><code>#!/usr/bin/env python3\n# syscall_latency.py — Measure read() syscall latency\nfrom bcc import BPF\nimport time\n\nbpf_program = \"\"\"\n#include &lt;uapi/linux/ptrace.h&gt;\n\nBPF_HASH(start, u32);\nBPF_HISTOGRAM(dist);\n\nTRACEPOINT_PROBE(syscalls, sys_enter_read) {\n    u32 pid = bpf_get_current_pid_tgid() >> 32;\n    u64 ts = bpf_ktime_get_ns();\n    start.update(&pid, &ts);\n    return 0;\n}\n\nTRACEPOINT_PROBE(syscalls, sys_exit_read) {\n    u32 pid = bpf_get_current_pid_tgid() >> 32;\n    u64 *tsp = start.lookup(&pid);\n    if (tsp != 0) {\n        u64 delta = bpf_ktime_get_ns() - *tsp;\n        dist.log2l(delta / 1000);  // microseconds\n        start.delete(&pid);\n    }\n    return 0;\n}\n\"\"\"\n\nb = BPF(text=bpf_program)\nprint(\"Measuring read() latency... Ctrl+C for results\")\n\ntry:\n    time.sleep(10)\nexcept KeyboardInterrupt:\n    pass\n\nprint(\"\\nread() latency (microseconds):\")\nb[\"dist\"].print_log2_hist(\"usecs\")</code></pre>\n          <pre><code># Run\nsudo python3 hello_ebpf.py\nsudo python3 syscall_latency.py</code></pre>\n        "
    },
    {
      "title": "6. libbpf + CO-RE Advanced Development",
      "content": "\n          <p>BCC is great for prototyping, but production environments should use <strong>libbpf + CO-RE</strong>:</p>\n          <table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\">\n            <tr style=\"border-bottom:1px solid #30363d;\">\n              <th style=\"text-align:left; padding:0.5rem;\">Feature</th>\n              <th style=\"text-align:left; padding:0.5rem;\">BCC</th>\n              <th style=\"text-align:left; padding:0.5rem;\">libbpf + CO-RE</th>\n            </tr>\n            <tr style=\"border-bottom:1px solid #30363d;\">\n              <td style=\"padding:0.5rem;\">Compilation</td>\n              <td style=\"padding:0.5rem;\">At runtime (needs Clang/LLVM)</td>\n              <td style=\"padding:0.5rem;\">Once at build time</td>\n            </tr>\n            <tr style=\"border-bottom:1px solid #30363d;\">\n              <td style=\"padding:0.5rem;\">Target machine deps</td>\n              <td style=\"padding:0.5rem;\">Needs kernel headers</td>\n              <td style=\"padding:0.5rem;\">Only BTF info needed</td>\n            </tr>\n            <tr style=\"border-bottom:1px solid #30363d;\">\n              <td style=\"padding:0.5rem;\">Startup speed</td>\n              <td style=\"padding:0.5rem;\">Slow (compilation)</td>\n              <td style=\"padding:0.5rem;\">Fast (pre-compiled bytecode)</td>\n            </tr>\n            <tr style=\"border-bottom:1px solid #30363d;\">\n              <td style=\"padding:0.5rem;\">Resource usage</td>\n              <td style=\"padding:0.5rem;\">High (Clang ~100MB)</td>\n              <td style=\"padding:0.5rem;\">Low (~KB level)</td>\n            </tr>\n            <tr>\n              <td style=\"padding:0.5rem;\">Use case</td>\n              <td style=\"padding:0.5rem;\">Prototyping, one-off debugging</td>\n              <td style=\"padding:0.5rem;\">Production tools</td>\n            </tr>\n          </table>\n          <p><strong>CO-RE (Compile Once, Run Everywhere)</strong> uses BTF (BPF Type Format) to automatically adjust struct offsets at load time, so the same binary runs on different kernel versions.</p>\n          <pre><code># Verify kernel supports BTF\nls /sys/kernel/btf/vmlinux\n\n# libbpf project structure\nmy-ebpf-tool/\n├── src/\n│   ├── tool.bpf.c      # eBPF kernel program\n│   ├── tool.c           # Userspace program\n│   └── tool.h           # Shared type definitions\n├── Makefile\n└── vmlinux.h            # Generated by bpftool</code></pre>\n          <pre><code># Generate vmlinux.h (contains all kernel types)\nbpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h\n\n# Compile eBPF program\nclang -O2 -target bpf -g -c tool.bpf.c -o tool.bpf.o\n\n# Generate skeleton header\nbpftool gen skeleton tool.bpf.o > tool.skel.h</code></pre>\n        "
    },
    {
      "title": "7. Real-World Applications",
      "content": "\n          <h4>🌐 Networking — XDP High-Speed Packet Processing</h4>\n          <pre><code>// xdp_drop_icmp.bpf.c — Drop all ICMP packets\n#include \"vmlinux.h\"\n#include &lt;bpf/bpf_helpers.h&gt;\n\nSEC(\"xdp\")\nint xdp_drop_icmp(struct xdp_md *ctx) {\n    void *data = (void *)(long)ctx->data;\n    void *data_end = (void *)(long)ctx->data_end;\n\n    struct ethhdr *eth = data;\n    if ((void *)(eth + 1) > data_end)\n        return XDP_PASS;\n\n    if (eth->h_proto != __constant_htons(ETH_P_IP))\n        return XDP_PASS;\n\n    struct iphdr *ip = (void *)(eth + 1);\n    if ((void *)(ip + 1) > data_end)\n        return XDP_PASS;\n\n    if (ip->protocol == IPPROTO_ICMP)\n        return XDP_DROP;\n\n    return XDP_PASS;\n}</code></pre>\n\n          <h4>🔒 Security — Detecting Suspicious Behavior</h4>\n          <p>Use eBPF to monitor sensitive file access, privilege escalation, etc. Related projects:</p>\n          <ul>\n            <li><strong>Falco</strong> — Runtime threat detection</li>\n            <li><strong>Tetragon</strong> — Cilium's security observability engine</li>\n            <li><strong>Tracee</strong> — Container security tracing</li>\n          </ul>\n\n          <h4>📊 Performance Analysis — Full System Diagnostics</h4>\n          <pre><code># CPU flamegraph\nsudo profile-bpfcc -F 99 30 > profile.out\n# Use with flamegraph.pl to generate SVG\n\n# I/O latency heatmap\nsudo biolatency-bpfcc -m\n\n# Memory leak tracing\nsudo memleak-bpfcc -p PID\n\n# TCP retransmission tracing\nsudo tcpretrans-bpfcc\n\n# Filesystem latency\nsudo ext4slower-bpfcc 1</code></pre>\n\n          <h4>📚 Recommended Learning Path</h4>\n          <ol>\n            <li>Start with <code>bpftrace</code> one-liners to build intuition</li>\n            <li>Use BCC ready-made tools to diagnose real problems</li>\n            <li>Write custom tracing tools with BCC Python</li>\n            <li>Learn libbpf + CO-RE for production-grade tools</li>\n            <li>Specialize in a domain (XDP networking, LSM security)</li>\n          </ol>\n          <p><strong>Recommended Reading:</strong></p>\n          <ul>\n            <li><a href=\"https://ebpf.io/\" target=\"_blank\">ebpf.io</a> — Official portal</li>\n            <li><a href=\"https://github.com/iovisor/bcc\" target=\"_blank\">iovisor/bcc</a> — BCC toolkit</li>\n            <li>Brendan Gregg, <em>BPF Performance Tools</em></li>\n            <li>Liz Rice, <em>Learning eBPF</em></li>\n          </ul>\n        "
    }
  ]
};
