/**
 * Topic: Systemd & Services
 */
const TOPIC_SYSTEMD = {
  "id": "systemd",
  "category": "core",
  "icon": "🔧",
  "title": "Systemd & Services",
  "description": "The Linux init system & service manager — units, service management, writing unit files, dependencies & targets, timers & socket activation, resource control/sandboxing, and the journal",
  "keywords": [
    "systemd", "service", "systemctl", "journalctl", "unit", "unit file",
    "target", "runlevel", "daemon", "init", "pid 1", "enable", "disable",
    "mask", "daemon-reload", "type", "execstart", "restart", "wants",
    "requires", "after", "before", "timer", "socket activation", "slice",
    "cgroup", "sandboxing", "hardening", "protectsystem", "privatetmp",
    "systemd-analyze", "journal", "boot", "drop-in"
  ],
  "sections": [
    {
      "title": "1. What is systemd?",
      "content": "<p><strong>systemd</strong> is the init system and service manager used by most modern Linux distributions. It is the first process the kernel starts (<strong>PID 1</strong>), and it is responsible for bringing the system up, starting and supervising services, managing dependencies, and shutting the system down cleanly.</p><h4>What it replaced</h4><pre><code># Old SysV init: sequential shell scripts in /etc/init.d, numbered symlinks\n# in /etc/rc?.d, slow serial boot, no real dependency tracking or supervision.\n#\n# systemd: declarative \"unit\" files, PARALLELIZED boot based on dependencies,\n# process supervision (auto-restart), integrated logging, timers, resource\n# control via cgroups, and on-demand (socket/path) activation.</code></pre><h4>The central concept: units</h4><pre><code># Everything systemd manages is a \"unit\" -- a service, a timer, a mount, a\n# target, etc. Units are described by declarative text files and controlled\n# uniformly with 'systemctl'.\n\nsystemctl                     # list all active units\nsystemctl --failed            # units that failed to start\nsystemctl status              # overall system state + a unit tree</code></pre><h4>The toolset</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">Tool</th><th style=\"text-align:left; padding:0.5rem;\">Purpose</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>systemctl</code></td><td style=\"padding:0.5rem;\">Control units (start/stop/enable/status)</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>journalctl</code></td><td style=\"padding:0.5rem;\">Query the log journal</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>systemd-analyze</code></td><td style=\"padding:0.5rem;\">Analyze boot time &amp; verify units</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>systemd-cgtop</code></td><td style=\"padding:0.5rem;\">Live per-cgroup resource usage</td></tr><tr><td style=\"padding:0.5rem;\"><code>timedatectl</code> / <code>hostnamectl</code></td><td style=\"padding:0.5rem;\">Manage time / hostname</td></tr></table>"
    },
    {
      "title": "2. Unit Types & Files",
      "content": "<p>Units come in several types, each identified by a filename suffix. The unit type determines what systemd does with it.</p><h4>Unit types</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">Suffix</th><th style=\"text-align:left; padding:0.5rem;\">Manages</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>.service</code></td><td style=\"padding:0.5rem;\">A daemon / process (the most common)</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>.socket</code></td><td style=\"padding:0.5rem;\">A socket for on-demand (socket) activation</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>.timer</code></td><td style=\"padding:0.5rem;\">A scheduled trigger (cron replacement)</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>.target</code></td><td style=\"padding:0.5rem;\">A group of units / boot milestone</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>.mount</code> / <code>.automount</code></td><td style=\"padding:0.5rem;\">A filesystem mount point</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>.path</code></td><td style=\"padding:0.5rem;\">Activate a unit when a path changes</td></tr><tr><td style=\"padding:0.5rem;\"><code>.slice</code></td><td style=\"padding:0.5rem;\">A cgroup for grouping/limiting units</td></tr></table><h4>Where unit files live (precedence: later overrides earlier)</h4><pre><code>/usr/lib/systemd/system/     # shipped by packages (do NOT edit)\n/run/systemd/system/         # runtime-generated (volatile)\n/etc/systemd/system/         # YOUR local units & overrides (highest priority)\n\n# A file in /etc/ with the same name overrides the packaged one entirely.\n# After ANY change to unit files on disk:\nsudo systemctl daemon-reload</code></pre><h4>Inspecting & editing units the safe way</h4><pre><code>systemctl cat nginx.service        # show the effective unit file(s)\nsystemctl show nginx.service       # every resolved property\nsystemctl list-unit-files          # all units + their enabled state\n\n# Create a DROP-IN override instead of editing the packaged file:\nsudo systemctl edit nginx.service  # creates /etc/systemd/system/nginx.service.d/override.conf\n# (only put the [Section] + keys you want to change; systemd merges them)</code></pre>"
    },
    {
      "title": "3. Managing Services",
      "content": "<h4>The everyday commands</h4><pre><code>sudo systemctl start nginx         # start now\nsudo systemctl stop nginx          # stop now\nsudo systemctl restart nginx       # stop + start\nsudo systemctl reload nginx        # re-read config WITHOUT dropping connections\nsudo systemctl reload-or-restart nginx\n\nsudo systemctl enable nginx        # start automatically at boot\nsudo systemctl disable nginx       # don't start at boot\nsudo systemctl enable --now nginx  # enable AND start in one step</code></pre><h4>enable vs start vs mask</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">Command</th><th style=\"text-align:left; padding:0.5rem;\">Effect</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>start</code>/<code>stop</code></td><td style=\"padding:0.5rem;\">Act now, this boot only</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>enable</code>/<code>disable</code></td><td style=\"padding:0.5rem;\">Set whether it starts at boot (doesn't touch current state)</td></tr><tr><td style=\"padding:0.5rem;\"><code>mask</code>/<code>unmask</code></td><td style=\"padding:0.5rem;\">Completely block a unit — can't be started even manually</td></tr></table><h4>Status & queries (scriptable)</h4><pre><code>systemctl status nginx             # detailed state + recent log lines + cgroup\nsystemctl is-active nginx          # active / inactive / failed\nsystemctl is-enabled nginx         # enabled / disabled / masked\nsystemctl is-failed nginx\n\nsystemctl list-units --type=service            # running services\nsystemctl list-units --type=service --all      # incl. inactive\nsystemctl list-units --state=failed            # what's broken\n\n# is-active exits 0 when active -> handy in scripts:\nif systemctl is-active --quiet nginx; then echo up; fi</code></pre>"
    },
    {
      "title": "4. Writing Unit Files",
      "content": "<p>A service unit has three sections: <code>[Unit]</code> (metadata &amp; ordering), <code>[Service]</code> (how to run it), and <code>[Install]</code> (how it's enabled).</p><h4>A complete service unit</h4><pre><code># /etc/systemd/system/myapp.service\n[Unit]\nDescription=My Application\nAfter=network-online.target        # ordering: start after networking is up\nWants=network-online.target        # weak dependency\n\n[Service]\nType=simple                        # ExecStart is the main process\nUser=appuser\nGroup=appuser\nWorkingDirectory=/opt/myapp\nEnvironment=\"PORT=8080\" \"ENV=prod\"\nEnvironmentFile=/etc/myapp/env     # or load vars from a file\nExecStart=/opt/myapp/server\nExecReload=/bin/kill -HUP $MAINPID\nRestart=on-failure                 # auto-restart if it crashes\nRestartSec=5\n\n[Install]\nWantedBy=multi-user.target         # which target enabling hooks it into\n</code></pre><pre><code>sudo systemctl daemon-reload       # tell systemd to re-read unit files\nsudo systemctl enable --now myapp.service</code></pre><h4>Type= — how systemd tracks the main process</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">Type</th><th style=\"text-align:left; padding:0.5rem;\">Use for</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>simple</code></td><td style=\"padding:0.5rem;\">Process stays in foreground (default)</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>exec</code></td><td style=\"padding:0.5rem;\">Like simple, but \"started\" only after exec succeeds</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>forking</code></td><td style=\"padding:0.5rem;\">Traditional daemons that fork &amp; exit the parent</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>oneshot</code></td><td style=\"padding:0.5rem;\">Run once and exit (setup tasks); often + RemainAfterExit</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>notify</code></td><td style=\"padding:0.5rem;\">Service signals readiness via sd_notify()</td></tr><tr><td style=\"padding:0.5rem;\"><code>dbus</code></td><td style=\"padding:0.5rem;\">Ready when it takes a D-Bus name</td></tr></table><h4>Restart policies</h4><pre><code># Restart=  no | on-success | on-failure | on-abnormal | on-watchdog | always\n# For resilient daemons, 'on-failure' (or 'always') + RestartSec is typical.\n# Guard against crash loops:\nStartLimitIntervalSec=60\nStartLimitBurst=5          # give up after 5 restarts in 60s</code></pre>"
    },
    {
      "title": "5. Dependencies, Targets & Boot",
      "content": "<p>systemd boots in parallel, ordering units only where you declare a dependency. <strong>Targets</strong> group units and replace the old SysV runlevels.</p><h4>Dependency & ordering directives</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">Directive</th><th style=\"text-align:left; padding:0.5rem;\">Meaning</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>Wants=</code></td><td style=\"padding:0.5rem;\">Pull in another unit; OK if it fails (weak)</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>Requires=</code></td><td style=\"padding:0.5rem;\">Hard dependency; if it fails, we fail too</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>After=</code> / <code>Before=</code></td><td style=\"padding:0.5rem;\">Ordering only (not a dependency)</td></tr><tr><td style=\"padding:0.5rem;\"><code>BindsTo=</code></td><td style=\"padding:0.5rem;\">Like Requires, but also stops when the other stops</td></tr></table><pre><code># Note: dependency (Wants/Requires) and ordering (After/Before) are SEPARATE.\n# You usually need BOTH -- e.g. Wants=network-online.target AND\n# After=network-online.target.</code></pre><h4>Targets (the runlevel replacement)</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">Target</th><th style=\"text-align:left; padding:0.5rem;\">Equivalent</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>multi-user.target</code></td><td style=\"padding:0.5rem;\">Runlevel 3 — multi-user, no GUI</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>graphical.target</code></td><td style=\"padding:0.5rem;\">Runlevel 5 — with display manager</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>rescue.target</code></td><td style=\"padding:0.5rem;\">Single-user / maintenance</td></tr><tr><td style=\"padding:0.5rem;\"><code>emergency.target</code></td><td style=\"padding:0.5rem;\">Minimal shell, root fs read-only</td></tr></table><pre><code>systemctl get-default                 # current default target\nsudo systemctl set-default multi-user.target   # boot to console (no GUI)\nsudo systemctl isolate rescue.target  # switch target now\nsystemctl list-dependencies graphical.target   # what it pulls in</code></pre><h4>Analyzing boot</h4><pre><code>systemd-analyze                       # total boot time (firmware/kernel/userspace)\nsystemd-analyze blame                 # slowest units, longest first\nsystemd-analyze critical-chain        # the ordering path that gated boot\nsystemd-analyze plot > boot.svg       # visual timeline</code></pre>"
    },
    {
      "title": "6. Timers, Sockets & On-Demand Activation",
      "content": "<h4>Timers — the cron replacement</h4><pre><code># A timer triggers a matching .service. Two files work as a pair:\n\n# /etc/systemd/system/backup.timer\n[Unit]\nDescription=Nightly backup\n[Timer]\nOnCalendar=*-*-* 02:00:00      # daily at 02:00 (see systemd.time for syntax)\nPersistent=true                # run missed jobs after downtime\nRandomizedDelaySec=300         # spread load (0-5 min jitter)\n[Install]\nWantedBy=timers.target\n\n# /etc/systemd/system/backup.service\n[Service]\nType=oneshot\nExecStart=/usr/local/bin/backup.sh</code></pre><pre><code>sudo systemctl enable --now backup.timer\nsystemctl list-timers                 # all timers: next run, last run\nsystemctl status backup.timer\n# Advantages over cron: journal integration, dependency ordering, catch-up\n# for missed runs, and calendar syntax with time zones.</code></pre><h4>Socket activation — start a service on demand</h4><pre><code># systemd can listen on a socket and start the service only when a client\n# connects -- saving resources and speeding boot.\n\n# foo.socket\n[Socket]\nListenStream=8080\n[Install]\nWantedBy=sockets.target\n\n# foo.service  (same name; started when the socket receives a connection)\n[Service]\nExecStart=/opt/foo/server\n\nsudo systemctl enable --now foo.socket   # enable the SOCKET, not the service\n# systemd holds the port; the service spins up on first connection.</code></pre><h4>Path units</h4><pre><code># A .path unit activates a service when a file/dir appears or changes:\n[Path]\nPathExists=/var/spool/incoming/trigger   # or PathChanged=, DirectoryNotEmpty=</code></pre>"
    },
    {
      "title": "7. Resource Control & Sandboxing",
      "content": "<p>Because every service runs in its own cgroup, systemd can cap its resources and heavily sandbox it — turning a plain daemon into a hardened one with a few directives.</p><h4>Resource limits (cgroups)</h4><pre><code># In the [Service] section, or applied live with set-property:\nMemoryMax=512M                 # hard memory cap (OOM-kill if exceeded)\nMemoryHigh=400M                # soft throttle threshold\nCPUQuota=50%                   # at most half of one CPU\nTasksMax=100                   # cap number of tasks (fork-bomb guard)\nIOWeight=100                   # relative block-I/O share\n\nsudo systemctl set-property nginx.service MemoryMax=512M CPUQuota=50%\nsystemd-cgtop                  # watch per-service CPU/mem/IO live</code></pre><h4>Sandboxing / hardening directives</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">Directive</th><th style=\"text-align:left; padding:0.5rem;\">Effect</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>NoNewPrivileges=yes</code></td><td style=\"padding:0.5rem;\">Process can't gain privileges (e.g. setuid)</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>ProtectSystem=strict</code></td><td style=\"padding:0.5rem;\">Most of the filesystem becomes read-only</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>ProtectHome=yes</code></td><td style=\"padding:0.5rem;\">/home, /root hidden from the service</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>PrivateTmp=yes</code></td><td style=\"padding:0.5rem;\">Private /tmp, isolated from other processes</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\"><code>PrivateDevices=yes</code></td><td style=\"padding:0.5rem;\">No access to physical device nodes</td></tr><tr><td style=\"padding:0.5rem;\"><code>CapabilityBoundingSet=</code></td><td style=\"padding:0.5rem;\">Restrict Linux capabilities</td></tr></table><pre><code># Audit how exposed a service is (0.0 = perfect, 10 = wide open):\nsystemd-analyze security nginx.service\nsystemd-analyze security          # score every service</code></pre>"
    },
    {
      "title": "8. Logs, Debugging & the Journal",
      "content": "<p>systemd captures each unit's stdout/stderr into the <strong>journal</strong>, a structured, indexed log queried with <code>journalctl</code>.</p><h4>Querying the journal</h4><pre><code>journalctl -u nginx                # all logs for a unit\njournalctl -u nginx -f             # follow live (like tail -f)\njournalctl -u nginx --since \"1 hour ago\"\njournalctl -u nginx --since today --until \"10:00\"\njournalctl -b                      # this boot only\njournalctl -b -1                   # the PREVIOUS boot\njournalctl -p err                  # priority err and above (emerg..err)\njournalctl -k                      # kernel messages (dmesg)\njournalctl _PID=1234               # by field (structured filtering)\njournalctl -u nginx -o json-pretty # change output format</code></pre><h4>Debugging a failed unit</h4><pre><code>systemctl status myapp.service     # state + exit code + last log lines\njournalctl -xe                     # recent logs + explanatory hints (-x)\njournalctl -u myapp -e             # jump to the end of a unit's log\nsystemd-analyze verify myapp.service  # lint the unit file for errors\n\n# Common failure clues:\n#   \"code=exited, status=203/EXEC\"  -> ExecStart path wrong / not executable\n#   \"status=200/CHDIR\"              -> WorkingDirectory doesn't exist\n#   \"Start request repeated too quickly\" -> crash loop; check the app logs</code></pre><h4>Managing journal size & persistence</h4><pre><code>journalctl --disk-usage            # how much space the journal uses\nsudo journalctl --vacuum-size=500M # keep at most 500M\nsudo journalctl --vacuum-time=2weeks\n\n# Persistent journal across reboots (survives more than the current boot):\n#   /etc/systemd/journald.conf ->  Storage=persistent\n#   (needs /var/log/journal to exist)\nsudo mkdir -p /var/log/journal && sudo systemctl restart systemd-journald</code></pre><h4>User services</h4><pre><code># Per-user services need no root; managed with --user:\nsystemctl --user status\nsystemctl --user enable --now myapp.service   # unit in ~/.config/systemd/user/\nloginctl enable-linger $USER       # let user services run without a login session</code></pre><p><strong>References:</strong></p><ul><li><a href=\"https://www.freedesktop.org/software/systemd/man/latest/systemctl.html\" target=\"_blank\">systemctl(1) — man page</a></li><li><a href=\"https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html\" target=\"_blank\">systemd.service(5) — service unit reference</a></li><li><a href=\"https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html\" target=\"_blank\">systemd.exec(5) — sandboxing/resource directives</a></li><li><a href=\"https://www.freedesktop.org/software/systemd/man/latest/journalctl.html\" target=\"_blank\">journalctl(1) — man page</a></li><li><a href=\"https://www.freedesktop.org/software/systemd/man/latest/systemd.timer.html\" target=\"_blank\">systemd.timer(5) — timer reference</a></li></ul>"
    }
  ]
};
