/**
 * Topic: EEVDF (Earliest Eligible Virtual Deadline First)
 */
const TOPIC_EEVDF = {
  "id": "eevdf",
  "category": "kernel",
  "icon": "⏱️",
  "title": "EEVDF Scheduler",
  "description": "The Linux kernel scheduler revolution — from CFS to EEVDF (Earliest Eligible Virtual Deadline First), the algorithm that replaced the Completely Fair Scheduler in Linux 6.6",
  "keywords": [
    "eevdf", "cfs", "scheduler", "sched", "scheduling", "fair", "completely fair",
    "vruntime", "virtual deadline", "eligible", "lag", "latency", "nice",
    "weight", "timeslice", "preemption", "ingo molnar", "peter zijlstra",
    "linux 6.6", "sched_ext", "latency-nice", "run queue", "red-black tree",
    "slice", "request size", "cpu"
  ],
  "sections": [
    {
      "title": "1. From CFS to EEVDF",
      "content": "<p><strong>EEVDF</strong> stands for <strong>Earliest Eligible Virtual Deadline First</strong>. Starting with <strong>Linux 6.6</strong> (released late 2023), the <strong>Completely Fair Scheduler (CFS)</strong> — which had served the Linux community for over 15 years — was retired, and the EEVDF scheduling algorithm, driven by <strong>Ingo Molnar</strong> and <strong>Peter Zijlstra</strong>, took over as the default scheduler for normal tasks (the <code>SCHED_NORMAL</code> / fair class).</p><h4>Why replace CFS at all?</h4><p>CFS was excellent at one thing: throughput fairness. It divided CPU time proportionally to task weight and generally kept every task's accumulated runtime balanced. But it had a persistent weakness: <strong>latency</strong>. CFS had no first-class notion of \"this task needs to run <em>soon</em>, even if briefly.\" Interactive and latency-sensitive tasks were served by heuristics and tunables (<code>sched_min_granularity</code>, <code>sched_wakeup_granularity</code>, GENTLE_FAIR_SLEEPERS, ...) that grew fragile and hard to reason about over the years.</p><pre><code># The core problem CFS could not express cleanly:\n#\n#   Task A: a batch compiler job   -> wants lots of CPU, doesn't care when\n#   Task B: an audio thread        -> wants tiny slices, but ON TIME\n#\n# CFS gives both \"fair\" total time, but B may wait too long between slices\n# and glitch. EEVDF lets B ask for a shorter latency target and honors it\n# WITHOUT giving B more than its fair share overall.</code></pre><h4>The headline idea</h4><ul><li><strong>CFS answered:</strong> \"who has received the least CPU so far?\" → pick that task (smallest <code>vruntime</code>).</li><li><strong>EEVDF answers:</strong> \"among tasks that are <em>eligible</em> (haven't gotten ahead of their fair share), who has the earliest <em>virtual deadline</em>?\" → pick that one.</li></ul><p>EEVDF unifies fairness <em>and</em> latency into a single, well-defined algorithm from academic literature (Stoica &amp; Abdel-Wahab, 1995), replacing a pile of heuristics with one coherent model.</p>"
    },
    {
      "title": "2. Core Concepts: Lag, Eligibility, Virtual Deadline",
      "content": "<p>EEVDF rests on three tightly related ideas. Understanding them is understanding the whole scheduler.</p><h4>1. Virtual runtime & the fair share</h4><pre><code># Like CFS, each task accrues virtual runtime. In an ideal, perfectly fair\n# system, every runnable task would receive CPU time proportional to its\n# weight (derived from nice value). The scheduler tracks how far each task\n# is AHEAD of or BEHIND that ideal.</code></pre><h4>2. Lag — the fairness debt</h4><pre><code># lag = (fair share the task SHOULD have received) - (what it ACTUALLY got)\n#\n#   lag > 0  : task is OWED time  (it ran less than fair)  -> eligible\n#   lag < 0  : task got AHEAD     (it ran more than fair)  -> NOT eligible yet\n#   lag = 0  : exactly fair\n#\n# EEVDF's fairness guarantee is expressed directly in terms of bounded lag.\n# A task that overran is temporarily held back until time \"catches up\" and\n# its lag returns to >= 0.</code></pre><h4>3. Eligibility</h4><p>A task is <strong>eligible</strong> only when its lag is non-negative — i.e. it has not already consumed more than its fair share up to now. This is the \"Eligible\" in EEVDF. Ineligible tasks are simply skipped for selection until the virtual clock advances enough to make them eligible again.</p><h4>4. Virtual deadline</h4><pre><code># Each task requests a time slice of size 'r' (its request / slice length).\n# EEVDF assigns a virtual DEADLINE = virtual_eligible_time + (r / weight).\n#\n#   - A SMALLER requested slice  -> EARLIER deadline -> scheduled sooner,\n#     more often, in shorter bursts   (great for latency-sensitive tasks)\n#   - A LARGER requested slice   -> LATER deadline -> runs less often but\n#     in longer chunks               (great for throughput/batch tasks)</code></pre><h4>The selection rule</h4><p>Among all <strong>eligible</strong> tasks, EEVDF runs the one with the <strong>earliest virtual deadline</strong> — hence <em>Earliest Eligible Virtual Deadline First</em>. This single rule delivers proportional fairness (via eligibility/lag) and latency control (via the deadline computed from the requested slice).</p>"
    },
    {
      "title": "3. How EEVDF Picks the Next Task",
      "content": "<h4>The algorithm in plain steps</h4><pre><code># On every scheduling decision (tick, wakeup, or task blocking):\n#\n# 1. Advance the virtual clock based on total weight of runnable tasks.\n# 2. Determine which tasks are ELIGIBLE now  (lag >= 0).\n# 3. Among eligible tasks, choose the one with the EARLIEST virtual deadline.\n# 4. Run it for up to its requested slice 'r'.\n# 5. Charge the CPU time used, update its lag/vruntime, recompute deadline.\n# 6. Repeat.</code></pre><h4>Worked intuition</h4><pre><code>   Three tasks, equal weight. Audio (B) asks for a small slice; the two\n   compilers (A, C) ask for large slices.\n\n   eligible?   deadline (earlier = sooner)\n   ┌──────┬───────────┬──────────────────────────┐\n   │ A    │  yes      │  late   (big slice)        │\n   │ B    │  yes      │  EARLY  (small slice) ◄──── picked: earliest deadline\n   │ C    │  yes      │  late   (big slice)        │\n   └──────┴───────────┴──────────────────────────┘\n\n   B runs its short slice, glitch-free, then yields. A and C still get\n   their full fair share over time because B's total CPU stays bounded by\n   its lag budget -- it just gets its time in smaller, more timely pieces.</code></pre><h4>Data structure</h4><pre><code># CFS kept an rbtree keyed by vruntime (\"who is furthest behind\").\n# EEVDF keeps runnable tasks in an augmented red-black tree that lets the\n# scheduler efficiently find the earliest-deadline task AMONG the eligible\n# subset. The augmentation stores the min virtual deadline of each subtree,\n# so selection stays O(log n).</code></pre><h4>Preemption</h4><pre><code># A newly-woken task that is eligible and has an earlier virtual deadline\n# than the running task can preempt it. Because latency-sensitive tasks\n# request small slices, they naturally get earlier deadlines and thus\n# timely preemption -- no separate wakeup-granularity heuristic needed.</code></pre>"
    },
    {
      "title": "4. CFS vs EEVDF — Side by Side",
      "content": "<table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">Aspect</th><th style=\"text-align:left; padding:0.5rem;\">CFS (≤ 6.5)</th><th style=\"text-align:left; padding:0.5rem;\">EEVDF (≥ 6.6)</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Selection rule</td><td style=\"padding:0.5rem;\">Smallest vruntime (most behind)</td><td style=\"padding:0.5rem;\">Earliest deadline among eligible</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Fairness model</td><td style=\"padding:0.5rem;\">Balance accumulated vruntime</td><td style=\"padding:0.5rem;\">Bounded lag (formal guarantee)</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Latency handling</td><td style=\"padding:0.5rem;\">Heuristics &amp; tunables</td><td style=\"padding:0.5rem;\">First-class via requested slice</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Per-task latency hint</td><td style=\"padding:0.5rem;\">None (only nice)</td><td style=\"padding:0.5rem;\">latency-nice → slice size</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Key tunables</td><td style=\"padding:0.5rem;\">sched_min_granularity, wakeup_granularity</td><td style=\"padding:0.5rem;\">Largely removed / obsolete</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Data structure</td><td style=\"padding:0.5rem;\">rbtree keyed by vruntime</td><td style=\"padding:0.5rem;\">Augmented rbtree (min-deadline)</td></tr><tr><td style=\"padding:0.5rem;\">Complexity</td><td style=\"padding:0.5rem;\">O(log n)</td><td style=\"padding:0.5rem;\">O(log n)</td></tr></table><h4>What stayed the same</h4><ul><li>Both are <strong>weight-based, proportional-share</strong> schedulers driven by the <code>nice</code> value (nice −20…+19 maps to a weight table).</li><li>Both live in the <strong>fair scheduling class</strong> (<code>kernel/sched/fair.c</code>) serving <code>SCHED_NORMAL</code>, <code>SCHED_BATCH</code>, <code>SCHED_IDLE</code>.</li><li>Both still track a form of <strong>virtual runtime</strong> and integrate with load balancing, cgroups (CPU controller), and the wider scheduler infrastructure.</li></ul><h4>What changed for users</h4><ul><li>Interactive/latency-sensitive workloads generally feel more responsive under contention without manual tuning.</li><li>Several old CFS knobs are gone or no longer meaningful; scripts that poked <code>sched_*_granularity</code> in <code>/proc/sys/kernel</code> may find them absent.</li><li>A new per-task <strong>latency-nice</strong> control lets you bias a task toward lower latency (smaller slice) or higher throughput (larger slice).</li></ul>"
    },
    {
      "title": "5. Tuning & Observability",
      "content": "<h4>latency-nice: request lower latency per task</h4><pre><code># latency-nice is a per-task hint (range like nice: -20..19). LOWER values\n# request lower scheduling latency (shorter slice, earlier deadlines).\n# It does NOT grant more CPU -- only changes HOW the fair share is delivered.\n\n#include <sched.h>\nstruct sched_attr attr = {\n    .size            = sizeof(attr),\n    .sched_policy    = SCHED_NORMAL,\n    .sched_flags     = SCHED_FLAG_LATENCY_NICE ,\n    .sched_latency_nice = -10,   // bias toward low latency\n};\nsched_setattr(0, &attr, 0);\n\n# From the shell, chrt reports/sets scheduling attributes:\nchrt -p $$            # show current policy for this shell</code></pre><h4>Inspecting the scheduler</h4><pre><code># Per-task scheduling stats (vruntime, deadline, slice, etc.)\ncat /proc/<pid>/sched\n\n# System-wide fair-class scheduler state (very detailed)\nsudo cat /sys/kernel/debug/sched/debug\n\n# Remaining scheduler tunables under debugfs (EEVDF era)\nls /sys/kernel/debug/sched/\n#   base_slice_ns   <- the default request/slice length used by EEVDF\n\n# Read/adjust the base time slice (nanoseconds)\ncat /sys/kernel/debug/sched/base_slice_ns</code></pre><h4>Tracing scheduling decisions with eBPF</h4><pre><code># Run-queue latency histogram (how long tasks wait to get on-CPU)\nsudo runqlat-bpfcc\n\n# Watch context switches and pick decisions live\nsudo bpftrace -e 'tracepoint:sched:sched_switch {\n  printf(\"%s -> %s\\n\", args->prev_comm, args->next_comm); }'\n\n# Wakeup-to-run latency (scheduler responsiveness)\nsudo bpftrace -e 'tracepoint:sched:sched_wakeup { @q[args->comm] = nsecs; }\n  tracepoint:sched:sched_switch /@q[args->next_comm]/ {\n    printf(\"%s waited %d us\\n\", args->next_comm,\n           (nsecs - @q[args->next_comm])/1000);\n    delete(@q[args->next_comm]); }'</code></pre><h4>Checking which scheduler / kernel you run</h4><pre><code>uname -r                       # 6.6+ ships EEVDF as the fair scheduler\ngrep -i eevdf /sys/kernel/debug/sched/* 2>/dev/null\n# Note: there is no runtime switch between CFS and EEVDF -- EEVDF simply\n# IS the fair class from 6.6 onward. To run a different policy engine, see\n# sched_ext (BPF schedulers) in newer kernels.</code></pre>"
    },
    {
      "title": "6. Practical Impact & Further Reading",
      "content": "<h4>Who benefits</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">Workload</th><th style=\"text-align:left; padding:0.5rem;\">Effect under EEVDF</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Audio / real-time-ish media</td><td style=\"padding:0.5rem;\">Fewer glitches — timely short slices without extra CPU</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Desktop / interactive</td><td style=\"padding:0.5rem;\">More responsive under heavy background load</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Batch / compilation / HPC</td><td style=\"padding:0.5rem;\">Similar throughput; can request larger slices</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Mixed latency + throughput</td><td style=\"padding:0.5rem;\">Both served from one coherent model, less tuning</td></tr><tr><td style=\"padding:0.5rem;\">Latency-sensitive services</td><td style=\"padding:0.5rem;\">Per-task latency-nice replaces fragile hacks</td></tr></table><h4>Key takeaways</h4><ul><li>EEVDF = <strong>Earliest Eligible Virtual Deadline First</strong>; default fair scheduler since <strong>Linux 6.6</strong>, replacing CFS after 15+ years.</li><li>It selects the <strong>earliest virtual-deadline</strong> task among those that are <strong>eligible</strong> (non-negative lag), unifying fairness and latency.</li><li><strong>Requested slice size</strong> controls latency: smaller slice → earlier deadline → run sooner/more often, without exceeding fair share.</li><li>Replaces a decade of CFS latency heuristics with a formally-grounded algorithm; adds a per-task <strong>latency-nice</strong> knob.</li><li>Led by <strong>Ingo Molnar</strong> and <strong>Peter Zijlstra</strong>, based on the 1995 EEVDF paper.</li></ul><p><strong>References:</strong></p><ul><li><a href=\"https://lwn.net/Articles/925371/\" target=\"_blank\">LWN: An EEVDF CPU scheduler for Linux</a></li><li><a href=\"https://lwn.net/Articles/969062/\" target=\"_blank\">LWN: Completing the EEVDF scheduler</a></li><li><a href=\"https://docs.kernel.org/scheduler/sched-design-CFS.html\" target=\"_blank\">Linux Kernel: Scheduler documentation</a></li><li><a href=\"https://elixir.bootlin.com/linux/latest/source/kernel/sched/fair.c\" target=\"_blank\">kernel/sched/fair.c (EEVDF implementation)</a></li><li><a href=\"https://dl.acm.org/doi/10.1145/207502.207503\" target=\"_blank\">Stoica &amp; Abdel-Wahab (1995): Earliest Eligible Virtual Deadline First</a></li></ul>"
    }
  ]
};
