/**
 * Topic: Network Management
 */
const TOPIC_NETWORKING = {
  "id": "networking",
  "category": "networking",
  "icon": "🌐",
  "title": "Network Management",
  "description": "Configure and troubleshoot Linux networking — interfaces & the ip suite, addressing & routing, DNS, persistent config (NetworkManager/netplan), sockets, diagnostics, and firewalls",
  "keywords": [
    "network", "networking", "ip", "iproute2", "interface", "ip addr",
    "ip route", "routing", "gateway", "cidr", "subnet", "dhcp", "static ip",
    "dns", "resolv.conf", "hosts", "dig", "nslookup", "systemd-resolved",
    "networkmanager", "nmcli", "netplan", "ss", "netstat", "socket", "port",
    "ping", "traceroute", "mtr", "tcpdump", "firewall", "iptables",
    "nftables", "ufw", "firewalld", "nat", "bridge", "vlan", "bond"
  ],
  "sections": [
    {
      "title": "1. Interfaces & the ip Suite",
      "content": "<p>Modern Linux networking is driven by the <strong>iproute2</strong> toolset — the <code>ip</code> command — which replaced the legacy <code>ifconfig</code>/<code>route</code>/<code>netstat</code> tools.</p><h4>Viewing interfaces</h4><pre><code>ip addr show               # all interfaces + their IP addresses (alias: ip a)\nip -br addr                # brief one-line-per-interface summary\nip link show               # link layer (MAC, state, MTU)\nip -s link show eth0       # interface statistics (packets, errors, drops)</code></pre><h4>Interface naming</h4><pre><code># Predictable names (systemd/udev) encode the hardware location, so they\n# stay stable across reboots:\n#   eth0            legacy kernel name\n#   enp3s0          en = ethernet, p3 = PCI bus 3, s0 = slot 0\n#   wlp2s0          wl = wireless\n#   lo              loopback (127.0.0.1 / ::1)\nls /sys/class/net          # every interface the kernel sees</code></pre><h4>Bringing links up / down / changing them</h4><pre><code>sudo ip link set eth0 up          # enable the interface\nsudo ip link set eth0 down        # disable it\nsudo ip link set eth0 mtu 9000    # set MTU (e.g. jumbo frames)\nsudo ip link set eth0 address 02:11:22:33:44:55   # change MAC\n\n# Note: 'ip' changes are RUNTIME-only and lost on reboot. For persistence\n# use NetworkManager/netplan (section 4).</code></pre>"
    },
    {
      "title": "2. Addressing & Routing",
      "content": "<h4>IP addresses (CIDR)</h4><pre><code>sudo ip addr add 192.168.1.100/24 dev eth0    # add an address\nsudo ip addr del 192.168.1.100/24 dev eth0    # remove it\n\n# CIDR /24 = 255.255.255.0 -> 256 addresses, 254 usable hosts.\n#   /16 = 65k hosts, /30 = 2 usable (point-to-point links).</code></pre><h4>Routing table</h4><pre><code>ip route show              # the routing table (alias: ip r)\n#   default via 192.168.1.1 dev eth0        <- the DEFAULT GATEWAY\n#   192.168.1.0/24 dev eth0 proto kernel ... <- directly-connected subnet\n\nsudo ip route add default via 192.168.1.1        # set default gateway\nsudo ip route add 10.0.0.0/8 via 192.168.1.254   # a static route\nsudo ip route del 10.0.0.0/8\nip route get 8.8.8.8       # which route/interface would reach this IP?</code></pre><h4>Static vs DHCP</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\"></th><th style=\"text-align:left; padding:0.5rem;\">Static</th><th style=\"text-align:left; padding:0.5rem;\">DHCP</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Address</td><td style=\"padding:0.5rem;\">Fixed, set by you</td><td style=\"padding:0.5rem;\">Leased from a DHCP server</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Use for</td><td style=\"padding:0.5rem;\">Servers, routers</td><td style=\"padding:0.5rem;\">Clients, laptops</td></tr><tr><td style=\"padding:0.5rem;\">Gateway/DNS</td><td style=\"padding:0.5rem;\">Configured manually</td><td style=\"padding:0.5rem;\">Provided automatically</td></tr></table><h4>IP forwarding (routing between interfaces)</h4><pre><code># Turn a host into a router (also required for container/VM NAT):\nsudo sysctl -w net.ipv4.ip_forward=1\n# Persist in /etc/sysctl.d/99-forward.conf : net.ipv4.ip_forward = 1</code></pre>"
    },
    {
      "title": "3. DNS — Name Resolution",
      "content": "<p>DNS turns names into IP addresses. Linux resolves names via the <strong>NSS</strong> chain — usually checking <code>/etc/hosts</code> first, then DNS servers.</p><h4>The key files</h4><pre><code>/etc/hosts                 # static name -> IP mappings (checked first)\n#   127.0.0.1   localhost\n#   192.168.1.10 db.internal\n\n/etc/resolv.conf           # which DNS servers to query\n#   nameserver 1.1.1.1\n#   search example.com     # append this domain to bare names\n\n/etc/nsswitch.conf         # resolution ORDER:  hosts: files dns</code></pre><h4>Querying DNS</h4><pre><code>dig example.com            # full DNS query + answer section\ndig +short example.com     # just the IP(s)\ndig example.com MX         # mail records (A, AAAA, CNAME, TXT, NS, ...)\ndig @1.1.1.1 example.com   # query a SPECIFIC server\nhost example.com           # simpler output\nresolvectl query example.com   # via systemd-resolved</code></pre><h4>systemd-resolved</h4><pre><code># On many distros /etc/resolv.conf is managed by systemd-resolved (a stub\n# at 127.0.0.53). Inspect the REAL upstream servers with:\nresolvectl status\nresolvectl statistics\n# Flush the resolver cache:\nsudo resolvectl flush-caches</code></pre>"
    },
    {
      "title": "4. Persistent Configuration",
      "content": "<p>Runtime <code>ip</code> commands vanish on reboot. Persistent config differs by distro — know which manager your system uses.</p><h4>NetworkManager (nmcli) — desktops, RHEL/Fedora, modern Ubuntu</h4><pre><code>nmcli device status                    # interfaces + their connections\nnmcli connection show                  # saved connection profiles\n\n# Configure a STATIC IP profile:\nsudo nmcli con add type ethernet con-name lan ifname eth0 \\\n     ip4 192.168.1.100/24 gw4 192.168.1.1\nsudo nmcli con mod lan ipv4.dns \"1.1.1.1 8.8.8.8\"\nsudo nmcli con up lan\n\nnmcli con mod lan ipv4.method auto     # switch back to DHCP\nnmtui                                  # curses text UI, if you prefer</code></pre><h4>netplan — Ubuntu server</h4><pre><code># /etc/netplan/01-netcfg.yaml  (YAML; indentation matters)\nnetwork:\n  version: 2\n  ethernets:\n    eth0:\n      addresses: [192.168.1.100/24]\n      routes:\n        - to: default\n          via: 192.168.1.1\n      nameservers:\n        addresses: [1.1.1.1, 8.8.8.8]\n\nsudo netplan try            # apply with auto-rollback if you lose access\nsudo netplan apply</code></pre><h4>The distro split</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">Distro</th><th style=\"text-align:left; padding:0.5rem;\">Typical manager</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">RHEL/Fedora</td><td style=\"padding:0.5rem;\">NetworkManager (nmcli)</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">Ubuntu Server</td><td style=\"padding:0.5rem;\">netplan (backends: systemd-networkd / NM)</td></tr><tr><td style=\"padding:0.5rem;\">Minimal/servers</td><td style=\"padding:0.5rem;\">systemd-networkd directly</td></tr></table>"
    },
    {
      "title": "5. Connections, Ports & Sockets",
      "content": "<p><code>ss</code> (socket statistics) is the modern replacement for <code>netstat</code> — it shows every network connection and listening port.</p><h4>ss — the essential command</h4><pre><code>ss -tuln                   # TCP+UDP, listening, numeric (don't resolve names)\n#   -t TCP  -u UDP  -l listening  -n numeric  -p show process  -a all\n\nss -tlnp                   # what's LISTENING + which process owns it\nss -tn state established   # active TCP connections\nss -tn dst 10.0.0.5        # connections to a specific host\nss -s                      # summary counts by socket type</code></pre><h4>Who owns a port?</h4><pre><code>sudo ss -tlnp | grep :8080         # process listening on 8080\nsudo lsof -i :8080                 # same, via lsof\nsudo fuser 8080/tcp                # PID(s) using the port\n\n# Ports 0-1023 are 'privileged' (need root to bind). 1024+ are ephemeral/user.</code></pre><h4>Legacy equivalents</h4><pre><code>netstat -tlnp              # old equivalent of ss -tlnp (may need net-tools)\n# Prefer 'ss' -- it's faster and installed by default on modern systems.</code></pre>"
    },
    {
      "title": "6. Diagnostics & Troubleshooting",
      "content": "<h4>Layered troubleshooting</h4><pre><code># Work up the stack: link -> IP -> routing -> DNS -> application.\nip -br link                        # 1. is the interface UP?\nip -br addr                        # 2. do I have an IP?\nip route                           # 3. is there a default gateway?\nping -c3 192.168.1.1               # 4. can I reach the gateway? (raw IP)\nping -c3 1.1.1.1                   # 5. the internet by IP? (routing OK)\ndig example.com                    # 6. does DNS resolve? (name issue vs net)\ncurl -v https://example.com        # 7. does the app/TLS layer work?</code></pre><h4>Path & reachability</h4><pre><code>traceroute example.com     # each hop toward the destination\nmtr example.com            # live traceroute + packet loss per hop (great!)\nping -M do -s 1472 host    # test path MTU (don't-fragment)</code></pre><h4>Packet capture (tcpdump)</h4><pre><code>sudo tcpdump -i eth0 port 80              # HTTP traffic on eth0\nsudo tcpdump -i any host 10.0.0.5         # to/from a specific host\nsudo tcpdump -i eth0 -w capture.pcap      # save for Wireshark analysis\nsudo tcpdump -i eth0 -n 'tcp[tcpflags] & tcp-syn != 0'   # SYNs only\n# -n skips name resolution; filters use BPF syntax (see the eBPF/XDP topics\n# for how the kernel matches these packets efficiently).</code></pre>"
    },
    {
      "title": "7. Firewalls",
      "content": "<p>Linux packet filtering runs in the kernel via <strong>netfilter</strong>. <code>nftables</code> is the modern framework; <code>iptables</code> is the legacy front-end; <code>ufw</code> and <code>firewalld</code> are friendlier wrappers.</p><h4>nftables (modern default)</h4><pre><code>sudo nft list ruleset                     # show all rules\nsudo nft add table inet filter\nsudo nft add chain inet filter input '{ type filter hook input priority 0; policy drop; }'\nsudo nft add rule inet filter input tcp dport 22 accept   # allow SSH\nsudo nft add rule inet filter input ct state established,related accept</code></pre><h4>iptables (legacy, still common)</h4><pre><code>sudo iptables -L -n -v             # list rules with packet counts\nsudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT   # allow SSH\nsudo iptables -A INPUT -s 10.0.0.5 -j DROP           # block an IP\nsudo iptables -P INPUT DROP        # default-deny inbound (careful: keep SSH!)\n# Rules are runtime-only; persist with iptables-save / netfilter-persistent.</code></pre><h4>Friendly wrappers</h4><pre><code># ufw (Debian/Ubuntu)\nsudo ufw allow 80/tcp\nsudo ufw allow from 192.168.1.0/24 to any port 22\nsudo ufw enable ; sudo ufw status verbose\n\n# firewalld (RHEL/Fedora) -- zone-based\nsudo firewall-cmd --add-service=http --permanent\nsudo firewall-cmd --add-port=8080/tcp --permanent\nsudo firewall-cmd --reload ; sudo firewall-cmd --list-all</code></pre><h4>NAT in one line (masquerade)</h4><pre><code># Share one public IP with an internal network (also what Docker/VMs do):\nsudo nft add rule inet nat postrouting oif eth0 masquerade\n# (requires net.ipv4.ip_forward=1 from section 2)</code></pre>"
    },
    {
      "title": "8. Advanced Networking",
      "content": "<h4>Bridges, bonds & VLANs</h4><pre><code># Bridge: a virtual switch joining interfaces (used by VMs/containers)\nsudo ip link add br0 type bridge\nsudo ip link set eth0 master br0\nsudo ip link set br0 up\n\n# Bond: aggregate NICs for redundancy/throughput (link aggregation)\nsudo ip link add bond0 type bond mode 802.3ad\nsudo ip link set eth0 master bond0\nsudo ip link set eth1 master bond0\n\n# VLAN: tag traffic to separate logical networks on one wire\nsudo ip link add link eth0 name eth0.100 type vlan id 100</code></pre><h4>Network namespaces</h4><pre><code># A network namespace is an isolated network stack -- the foundation of\n# container networking. Each has its own interfaces, routes, and firewall.\nsudo ip netns add test\nsudo ip netns exec test ip addr        # run a command inside the namespace\nsudo ip netns list\n# Docker/Podman create a namespace per container and wire it to a bridge.</code></pre><h4>Related topics</h4><table style=\"width:100%; border-collapse:collapse; margin:1rem 0;\"><tr style=\"border-bottom:1px solid #30363d;\"><th style=\"text-align:left; padding:0.5rem;\">For…</th><th style=\"text-align:left; padding:0.5rem;\">See topic</th></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">The physical layer &amp; NIC features</td><td style=\"padding:0.5rem;\">Ethernet</td></tr><tr style=\"border-bottom:1px solid #30363d;\"><td style=\"padding:0.5rem;\">High-speed fabric / RDMA</td><td style=\"padding:0.5rem;\">InfiniBand</td></tr><tr><td style=\"padding:0.5rem;\">Fast in-kernel packet processing</td><td style=\"padding:0.5rem;\">XDP / eBPF</td></tr></table><p><strong>References:</strong></p><ul><li><a href=\"https://man7.org/linux/man-pages/man8/ip.8.html\" target=\"_blank\">ip(8) — the iproute2 command</a></li><li><a href=\"https://man7.org/linux/man-pages/man8/ss.8.html\" target=\"_blank\">ss(8) — socket statistics</a></li><li><a href=\"https://wiki.nftables.org/\" target=\"_blank\">nftables wiki</a></li><li><a href=\"https://networkmanager.dev/docs/\" target=\"_blank\">NetworkManager documentation</a></li><li><a href=\"https://netplan.io/reference\" target=\"_blank\">netplan reference</a></li></ul>"
    }
  ]
};
