/**
 * Topic: Git
 */
const TOPIC_GIT = {
  "id": "git",
  "icon": "🔀",
  "title": "Git",
  "description": "Master Git version control — from repository setup to advanced collaboration, organized by workflow category",
  "sections": [
    {
      "title": "1. Repository Setup",
      "content": "<pre><code># Initialize a new repository\ngit init\ngit init --bare /srv/repos/project.git   # server-side (no working dir)\n\n# Clone existing\ngit clone https://github.com/user/repo.git\ngit clone git@github.com:user/repo.git          # SSH\ngit clone --depth 1 https://...                  # shallow (latest only)\ngit clone --branch v2.0 https://...              # specific branch/tag\ngit clone --recurse-submodules https://...       # with submodules\n\n# Configure identity (per-repo or global)\ngit config user.name \"Your Name\"\ngit config user.email \"you@example.com\"\ngit config --global init.defaultBranch main\n\n# .gitignore\necho \"*.pyc\" >> .gitignore\necho \"__pycache__/\" >> .gitignore\necho \".env\" >> .gitignore\necho \"build/\" >> .gitignore\ngit add .gitignore\n\n# .gitattributes (line endings, LFS, diff)\necho \"*.bin binary\" >> .gitattributes\necho \"*.png filter=lfs diff=lfs merge=lfs\" >> .gitattributes\n\n# Submodules\ngit submodule add https://github.com/lib/sdk.git vendor/sdk\ngit submodule update --init --recursive</code></pre>"
    },
    {
      "title": "2. Stage & Commit",
      "content": "<pre><code># Check status\ngit status\ngit status -sb              # short + branch info\n\n# Stage files\ngit add file.txt            # specific file\ngit add src/                # directory\ngit add -A                  # all changes (new + modified + deleted)\ngit add -p                  # interactive hunk-by-hunk staging\ngit add -u                  # only modified/deleted (not new)\n\n# Unstage (undo add)\ngit restore --staged file.txt\ngit reset HEAD file.txt     # older syntax\n\n# Commit\ngit commit -m \"feat: add new feature\"\ngit commit -am \"fix: quick fix\"         # stage tracked + commit\ngit commit --allow-empty -m \"trigger CI\" # empty commit\ngit commit -v                            # show diff in editor\n\n# Amend last commit (rewrite history)\ngit commit --amend                       # edit message + add staged\ngit commit --amend --no-edit             # keep message, add staged\ngit commit --amend --author=\"Name <email>\"\n\n# View what's staged vs unstaged\ngit diff              # unstaged changes\ngit diff --staged     # staged changes (same as --cached)\ngit diff HEAD         # all changes vs last commit</code></pre>"
    },
    {
      "title": "3. Branch Management",
      "content": "<pre><code># List branches\ngit branch                  # local\ngit branch -r               # remote\ngit branch -a               # all\ngit branch -v               # with last commit\ngit branch --merged         # branches merged into current\ngit branch --no-merged      # unmerged branches\n\n# Create branch\ngit branch feature-x                    # create (don't switch)\ngit switch -c feature-x                 # create + switch (modern)\ngit checkout -b feature-x               # create + switch (legacy)\ngit switch -c feature-x origin/main     # from specific base\n\n# Switch branch\ngit switch main\ngit switch -                            # previous branch (like cd -)\n\n# Rename branch\ngit branch -m old-name new-name\ngit branch -m new-name                  # rename current\n\n# Delete branch\ngit branch -d feature-x                 # safe (must be merged)\ngit branch -D feature-x                 # force delete\ngit push origin --delete feature-x      # delete remote branch\n\n# Track remote branch\ngit switch --track origin/feature-x\ngit branch -u origin/main               # set upstream for current</code></pre>"
    },
    {
      "title": "4. Merge & Rebase",
      "content": "<h4>Merge Strategies</h4>\n<pre><code># Fast-forward (linear, no merge commit)\ngit switch main\ngit merge feature-x                     # FF if possible\n\n# No fast-forward (always merge commit)\ngit merge --no-ff feature-x\n\n# Squash merge (combine all feature commits into one)\ngit merge --squash feature-x\ngit commit -m \"feat: add feature X\"\n\n# Abort conflicted merge\ngit merge --abort</code></pre>\n<h4>Conflict Resolution</h4>\n<pre><code># After conflict:\n# 1. Edit files (look for &lt;&lt;&lt;&lt;&lt;&lt;&lt; / ======= / &gt;&gt;&gt;&gt;&gt;&gt;&gt;)\n# 2. Stage resolved files\ngit add resolved-file.txt\n# 3. Complete merge\ngit commit\n\n# Use a merge tool\ngit mergetool                # opens configured tool\ngit config merge.tool vimdiff</code></pre>\n<h4>Rebase</h4>\n<pre><code># Rebase: replay commits on top of another branch\ngit switch feature-x\ngit rebase main\n# Result: feature-x commits re-applied on tip of main (linear history)\n\n# Interactive rebase (rewrite history)\ngit rebase -i HEAD~5\n# pick   abc1234 Add feature        ← keep\n# squash def5678 Fix typo           ← combine with above\n# reword 789abcd Update docs        ← edit message\n# drop   111aaaa Remove debug code  ← remove entirely\n# edit   222bbbb Refactor           ← pause for changes\n\n# Rebase onto (move branch base)\ngit rebase --onto main feature-a feature-b\n\n# Abort rebase\ngit rebase --abort\n\n# Continue after fixing conflicts\ngit rebase --continue</code></pre>\n<h4>Rule: Never rebase shared/pushed branches</h4>"
    },
    {
      "title": "5. Remote Operations",
      "content": "<pre><code># Manage remotes\ngit remote -v                            # list remotes\ngit remote add origin git@github.com:user/repo.git\ngit remote add upstream https://github.com/original/repo.git\ngit remote set-url origin git@github.com:user/new-repo.git\ngit remote remove upstream\ngit remote rename origin github\n\n# Fetch (download, don't merge)\ngit fetch origin                        # all branches\ngit fetch --all                         # all remotes\ngit fetch --prune                       # remove stale remote branches\ngit fetch origin main                   # specific branch\n\n# Pull (fetch + merge/rebase)\ngit pull                                # fetch + merge\ngit pull --rebase                       # fetch + rebase (cleaner)\ngit pull --rebase origin main\ngit pull --ff-only                      # only if fast-forward possible\n\n# Push\ngit push origin main\ngit push -u origin feature-x            # set upstream + push\ngit push --tags                         # push all tags\ngit push --force-with-lease             # safe force push\ngit push origin --delete feature-x      # delete remote branch\n\n# Forking workflow (keep fork in sync)\ngit fetch upstream\ngit switch main\ngit merge upstream/main\ngit push origin main</code></pre>"
    },
    {
      "title": "6. History & Inspection",
      "content": "<pre><code># Log (view history)\ngit log --oneline --graph --all --decorate\ngit log -5                              # last 5 commits\ngit log --stat                          # files changed per commit\ngit log -p                              # full diff per commit\ngit log --author=\"name\"                 # by author\ngit log --since=\"2024-01-01\"            # by date\ngit log --grep=\"fix\"                    # search commit messages\ngit log -- path/to/file                 # history of specific file\ngit log --follow -- old-name.py         # follow renames\ngit log main..feature-x                 # commits in feature not in main\n\n# Show specific commit\ngit show abc1234\ngit show HEAD~3                         # 3 commits ago\ngit show main:src/app.py                # file content at branch tip\n\n# Blame (who changed each line)\ngit blame src/app.py\ngit blame -L 10,20 src/app.py           # lines 10-20 only\n\n# Diff between branches/commits\ngit diff main..feature-x\ngit diff HEAD~3..HEAD\ngit diff --stat main..feature-x         # summary only\ngit diff --name-only HEAD~1             # just filenames\n\n# Search content\ngit grep \"TODO\" -- \"*.py\"               # search in tracked files\ngit log -S \"function_name\"              # find when string was added/removed (pickaxe)\ngit log -G \"regex_pattern\"              # regex search in diffs</code></pre>"
    },
    {
      "title": "7. Undo & Recovery",
      "content": "<h4>Discard Changes</h4>\n<pre><code># Discard unstaged changes in working directory\ngit restore file.txt                    # specific file\ngit restore .                           # all files\ngit checkout -- file.txt                # older syntax\n\n# Discard all (staged + unstaged) — DANGEROUS\ngit reset --hard HEAD\ngit checkout -f</code></pre>\n<h4>Reset (Move HEAD)</h4>\n<pre><code># Soft: undo commit, keep changes staged\ngit reset --soft HEAD~1\n\n# Mixed (default): undo commit, keep changes unstaged\ngit reset HEAD~1\n\n# Hard: undo commit, discard all changes — DANGEROUS\ngit reset --hard HEAD~1\n\n# Reset to specific commit\ngit reset --hard abc1234</code></pre>\n<h4>Revert (Safe Undo — Creates New Commit)</h4>\n<pre><code># Undo a commit by creating a new inverse commit\ngit revert abc1234\ngit revert HEAD                         # undo last commit\ngit revert HEAD~3..HEAD                 # undo last 3 commits\ngit revert --no-commit abc1234          # stage revert without committing</code></pre>\n<h4>Reflog (Last Resort Recovery)</h4>\n<pre><code># Git keeps ALL HEAD movements (even after reset --hard)\ngit reflog\n# abc1234 HEAD@{0}: reset: moving to HEAD~1\n# def5678 HEAD@{1}: commit: Add feature\n\n# Recover \"lost\" commits\ngit switch -c recovered def5678\ngit reset --hard HEAD@{2}               # go back to 2 operations ago\n\n# Recover deleted branch\ngit reflog | grep \"feature-x\"\ngit switch -c feature-x abc1234</code></pre>"
    },
    {
      "title": "8. Stash & Temporary Work",
      "content": "<pre><code># Save uncommitted work temporarily\ngit stash                               # stash tracked files\ngit stash push -m \"WIP: feature X\"      # with message\ngit stash -u                            # include untracked files\ngit stash -a                            # include ignored files too\ngit stash push -- file1.py file2.py     # stash specific files\n\n# List stashes\ngit stash list\n# stash@{0}: WIP on main: abc1234 last commit message\n# stash@{1}: On feature: def5678 WIP: feature X\n\n# Apply stash\ngit stash pop                           # apply + remove top stash\ngit stash apply                         # apply but keep in stash\ngit stash apply stash@{2}              # apply specific stash\ngit stash pop --index                   # restore staged state too\n\n# View stash content\ngit stash show                          # summary\ngit stash show -p                       # full diff\ngit stash show -p stash@{1}\n\n# Delete stash\ngit stash drop stash@{0}               # remove specific\ngit stash clear                         # remove ALL stashes\n\n# Create branch from stash\ngit stash branch new-feature stash@{0} # apply stash on new branch</code></pre>"
    },
    {
      "title": "9. Commit Management",
      "content": "<h4>Cherry-Pick</h4>\n<pre><code># Apply specific commit(s) to current branch\ngit cherry-pick abc1234\ngit cherry-pick abc1234 def5678         # multiple\ngit cherry-pick --no-commit abc1234     # stage but don't commit\ngit cherry-pick -x abc1234             # add \"(cherry picked from ...)\" to message\ngit cherry-pick --abort                 # cancel</code></pre>\n<h4>Rewrite History</h4>\n<pre><code># Interactive rebase to edit past commits\ngit rebase -i HEAD~5\n\n# Split a commit into two\n# In rebase: mark commit as \"edit\"\ngit reset HEAD~1                        # unstage the commit\ngit add file1.py && git commit -m \"part 1\"\ngit add file2.py && git commit -m \"part 2\"\ngit rebase --continue\n\n# Change author of past commits\ngit rebase -i HEAD~3\n# mark as \"edit\", then:\ngit commit --amend --author=\"New Name <new@email.com>\"\ngit rebase --continue\n\n# Remove file from all history (sensitive data leaked)\ngit filter-repo --path secrets.env --invert-paths\n# (requires git-filter-repo: pip install git-filter-repo)</code></pre>\n<h4>Tags</h4>\n<pre><code># Annotated tag (recommended for releases)\ngit tag -a v1.0.0 -m \"Release 1.0.0\"\ngit tag -a v1.0.1 -m \"Patch release\" abc1234   # tag specific commit\n\n# Lightweight tag (just a pointer)\ngit tag v1.0.0-rc1\n\n# List / delete / push tags\ngit tag -l \"v1.*\"\ngit tag -d v1.0.0\ngit push origin v1.0.0                 # push specific tag\ngit push origin --tags                 # push all tags\ngit push origin --delete v1.0.0        # delete remote tag</code></pre>"
    },
    {
      "title": "10. Advanced Git",
      "content": "<h4>Bisect (Binary Search for Bug)</h4>\n<pre><code># Find which commit introduced a bug\ngit bisect start\ngit bisect bad                          # current is broken\ngit bisect good v1.0                    # this was working\n# Git checks out middle commit — test it:\ngit bisect good   # or   git bisect bad\n# Repeat until found\ngit bisect reset                        # return to original\n\n# Automated bisect with test script\ngit bisect start HEAD v1.0\ngit bisect run ./test-script.sh         # exits 0=good, 1=bad</code></pre>\n<h4>Worktrees (Multiple Checkouts)</h4>\n<pre><code># Work on multiple branches simultaneously (no stash needed)\ngit worktree add ../hotfix-branch hotfix/urgent\ncd ../hotfix-branch\n# ... fix bug, commit, push ...\ngit worktree remove ../hotfix-branch\n\ngit worktree list                       # show all worktrees</code></pre>\n<h4>Sparse Checkout (Partial Clone)</h4>\n<pre><code># Clone only specific directories (monorepo)\ngit clone --filter=blob:none --sparse https://github.com/big/monorepo.git\ncd monorepo\ngit sparse-checkout set services/my-service libs/shared</code></pre>\n<h4>Git Objects & Internals</h4>\n<pre><code># 4 object types (all content-addressed by SHA-1):\n# blob   — file content\n# tree   — directory listing\n# commit — snapshot + metadata\n# tag    — named pointer to commit\n\ngit cat-file -t abc1234                 # show type\ngit cat-file -p abc1234                 # show content\ngit ls-tree HEAD                        # show current tree\ngit rev-parse HEAD                      # resolve to SHA\ngit count-objects -vH                   # repo size stats</code></pre>"
    },
    {
      "title": "11. Data & AI Project Commands",
      "content": "<h4>Git LFS (Large File Storage)</h4>\n<pre><code># Track large files (models, datasets, binaries)\ngit lfs install\ngit lfs track \"*.bin\"\ngit lfs track \"*.h5\"\ngit lfs track \"datasets/**\"\ngit add .gitattributes\n\n# Status\ngit lfs ls-files                        # list tracked LFS files\ngit lfs status\ngit lfs env                             # show LFS config\n\n# Fetch/pull LFS files\ngit lfs fetch --all\ngit lfs pull</code></pre>\n<h4>Handling Jupyter Notebooks</h4>\n<pre><code># Clean notebook outputs before commit\npip install nbstripout\nnbstripout --install                    # auto-strip on commit\n\n# Or in .gitattributes:\n*.ipynb filter=nbstripout</code></pre>\n<h4>Monorepo Patterns</h4>\n<pre><code># Sparse checkout for team-specific code\ngit sparse-checkout set ml-pipeline/ shared-libs/\n\n# Path-based CODEOWNERS\n# .github/CODEOWNERS:\n# /ml-pipeline/  @ml-team\n# /infra/        @platform-team\n# /docs/         @docs-team</code></pre>\n<h4>CI/CD Integration</h4>\n<pre><code># Get info for CI scripts\ngit rev-parse --short HEAD              # short SHA for image tags\ngit describe --tags --always            # version from nearest tag\ngit log -1 --format=\"%H %s\"            # latest commit info\ngit diff --name-only HEAD~1             # changed files (for selective CI)\ngit branch --show-current               # current branch name</code></pre>"
    },
    {
      "title": "12. Collaboration & Cleanup",
      "content": "<h4>Code Review Workflow</h4>\n<pre><code># Create PR-ready branch\ngit switch -c feature/my-feature main\n# ... develop ...\ngit push -u origin feature/my-feature\n# → Open PR on GitHub/GitLab\n\n# Update PR after review feedback\ngit add -A && git commit -m \"address review comments\"\ngit push\n# Or amend + force push (if single commit):\ngit commit --amend --no-edit && git push --force-with-lease\n\n# Sync PR branch with main (rebase preferred)\ngit fetch origin main\ngit rebase origin/main\ngit push --force-with-lease</code></pre>\n<h4>Cleanup</h4>\n<pre><code># Remove merged branches\ngit branch --merged main | grep -v \"main\" | xargs git branch -d\ngit fetch --prune                       # remove stale remote refs\n\n# Garbage collection\ngit gc --aggressive                     # compress objects\ngit prune                               # remove unreachable objects\n\n# Reduce repo size (remove old big files)\ngit filter-repo --strip-blobs-bigger-than 10M\n\n# Clean untracked files\ngit clean -n                            # dry run (show what would be removed)\ngit clean -fd                           # force remove dirs + files\ngit clean -fX                           # remove only ignored files</code></pre>\n<h4>Commit Message Convention</h4>\n<pre><code># Conventional Commits:\n# &lt;type&gt;(&lt;scope&gt;): &lt;short description&gt;\n#\n# Types: feat, fix, docs, style, refactor, perf, test, chore\n#\n# Examples:\nfeat(pcie): add AER error monitoring probe\nfix(storage): correct latency histogram bucket calculation\ndocs(ebpf): add development plan and test plan\nchore(deps): upgrade BCC to v0.30.0\n\n# Breaking change:\nfeat(api)!: change event schema to v2\n</code></pre>\n<h4>Useful Aliases</h4>\n<pre><code>git config --global alias.lg \"log --oneline --graph --all --decorate\"\ngit config --global alias.st \"status -sb\"\ngit config --global alias.co \"checkout\"\ngit config --global alias.br \"branch -vv\"\ngit config --global alias.last \"log -1 HEAD --stat\"\ngit config --global alias.unstage \"restore --staged\"\ngit config --global alias.amend \"commit --amend --no-edit\"\ngit config --global alias.wip \"commit -am 'WIP'\"</code></pre>\n<p><strong>References:</strong></p>\n<ul>\n  <li><a href=\"https://git-scm.com/doc\" target=\"_blank\">Git Official Documentation</a></li>\n  <li><a href=\"https://git-scm.com/book/en/v2\" target=\"_blank\">Pro Git Book (free)</a></li>\n  <li><a href=\"https://www.conventionalcommits.org/\" target=\"_blank\">Conventional Commits</a></li>\n  <li><a href=\"https://ohshitgit.com/\" target=\"_blank\">Oh Shit, Git!?!</a></li>\n</ul>"
    }
  ]
};
